"""Offline aggregator for the telemetry dashboard.

Reads:
- ``<consumer>/.ai-playbook-state/rule-events.jsonl`` (rule-event/v2 schema).
- The JSON output of ``scripts/caveman/stats.py`` (via direct import).
- ``configs/pricing.yaml`` (sha256-pinned at run time).

Writes a single sidecar at ``<consumer>/.ai-playbook/dashboard-data.js`` of the
form ``window.DASHBOARD_DATA = { ... };``. The browser loads it via
``<script src>`` from ``config-ui/index.html`` (``fetch()`` is blocked on
``file://``). Writes are atomic (temp + rename); torn JSONL lines are skipped
without crashing.

This module is invoked:
- Directly by developers: ``python -m scripts.telemetry.build_dashboard_data``.
- Automatically by ``scripts/apply_config.py`` as a post-hook on every
  successful config-bundle apply.

See:
- ``docs/concepts/telemetry-dashboard.md`` for the panel design.
- ``schemas/schema-dashboard-data-v1.json`` for the output contract.
- ``openspec/changes/telemetry-dashboard/`` for the change-tracked proposal.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Tunables.
# ---------------------------------------------------------------------------

# Output sidecar schema. Renderer rejects mismatches.
SCHEMA_VERSION = "dashboard-data/v1"

# Below this event count, the renderer shows the pedagogical empty state.
DEFAULT_EMPTY_STATE_THRESHOLD = 100

# Drift detection thresholds (design.md §Open Questions Q1, closed here).
# Cross-LLM disagreement: max minus min `by_llm` value exceeds this → drift.
CROSS_LLM_DRIFT_THRESHOLD = 0.10
# Per-LLM time-over-time delta: |current - prior| exceeds this → drift.
TIME_OVER_TIME_DRIFT_THRESHOLD = 0.05

# Per-rule sample-size floors for honesty meter and matrix drift detection.
HONESTY_MIN_EVENTS = 50
MATRIX_DRIFT_MIN_EVENTS = 30

# Friction panel: top-N rules and top-N override reasons per rule.
FRICTION_TOP_RULES = 5
FRICTION_TOP_REASONS = 3

# Cost methodology link (used by the renderer's cost panel tooltip).
# Relative to config-ui/index.html, which sits one level below the playbook
# docs tree (<consumer>/.ai-playbook/config-ui/ → ../docs/...). Must match the
# sibling TELEMETRY_DESIGN_DOC convention in config-ui/dashboard.js.
COST_METHODOLOGY_URL = "../docs/concepts/caveman-mode.md#cost-methodology"

# Health-emoji thresholds (driven by obey_rate_7d).
HEALTH_GREEN_FLOOR = 0.95
HEALTH_YELLOW_FLOOR = 0.85

# Pedagogical empty-state copy. Tech-writing polish lives in v2 candidates.
EMPTY_STATE_COPY = (
    "No telemetry yet. The dashboard becomes meaningful after ~100 rule-event/v2 "
    "events accumulate in this repo. Use the playbook as you normally would; "
    "the data lands on its own. See docs/concepts/telemetry-design.md for what "
    "each event records."
)

# Privacy guard: target_rel must look like a glob (contain '*' or end with a
# scrubbed marker). Anything that looks like a raw path is replaced.
_GLOB_LIKE = re.compile(r"[*?\[\]]")

# Single-line JS sidecar wrapper.
_JS_HEADER = "// generated by scripts/telemetry/build_dashboard_data.py — do not edit by hand\n"
_JS_PREFIX = "window.DASHBOARD_DATA = "
_JS_SUFFIX = ";\n"


# ---------------------------------------------------------------------------
# IO helpers.
# ---------------------------------------------------------------------------


def _utcnow() -> _dt.datetime:
    return _dt.datetime.now(_dt.UTC).replace(microsecond=0)


def _iso(dt: _dt.datetime) -> str:
    return dt.isoformat().replace("+00:00", "Z")


def _sha256_of_file(path: Path) -> str | None:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def _atomic_write(path: Path, payload: str) -> None:
    """Write ``payload`` to ``path`` atomically (temp + os.replace)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(payload, encoding="utf-8", newline="\n")
    os.replace(tmp, path)


def _scrub_target_rel(value: Any) -> str | None:
    """Return ``value`` if it looks like a glob, else replace with marker.

    Privacy invariant: individual file paths must never reach the sidecar.
    The playbook scrubs at write time; this is the second-line check at
    display time.
    """
    if not isinstance(value, str) or not value:
        return None
    if _GLOB_LIKE.search(value):
        return value
    # Common scrubbed sentinels (e.g. "*.env", "**/secrets/*") would have matched
    # above. Anything that looks like a literal path is suspicious.
    return "<scrub-violation>"


# ---------------------------------------------------------------------------
# State-dir resolution (reuses the rule_event_logger's contract).
# ---------------------------------------------------------------------------


def _resolve_state_dir(state_dir: Path | None, consumer_root: Path) -> Path:
    if state_dir is not None:
        return state_dir.expanduser().resolve()
    env = os.environ.get("AI_PLAYBOOK_STATE_DIR")
    if env:
        return Path(env).expanduser().resolve()
    return (consumer_root / ".ai-playbook-state").resolve()


def _default_consumer_root() -> Path:
    return Path.cwd().resolve()


def _default_output(consumer_root: Path) -> Path:
    return (consumer_root / ".ai-playbook" / "dashboard-data.js").resolve()


# ---------------------------------------------------------------------------
# JSONL streaming with tolerance.
# ---------------------------------------------------------------------------


@dataclass
class _ParsedEvents:
    events: list[dict] = field(default_factory=list)
    events_skipped: int = 0


def _iter_jsonl(path: Path) -> _ParsedEvents:
    out = _ParsedEvents()
    if not path.is_file():
        return out
    try:
        with path.open("r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    out.events_skipped += 1
                    continue
                if not isinstance(obj, dict):
                    out.events_skipped += 1
                    continue
                if obj.get("schema") != "rule-event/v2":
                    out.events_skipped += 1
                    continue
                out.events.append(obj)
    except OSError:
        return out
    return out


def _within_window(event: dict, start: _dt.datetime, end: _dt.datetime) -> bool:
    ts = event.get("timestamp")
    if not isinstance(ts, str):
        return False
    try:
        dt = _dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except ValueError:
        return False
    return start <= dt <= end


# ---------------------------------------------------------------------------
# Panel computation.
# ---------------------------------------------------------------------------


def _is_hero_incident(event: dict) -> bool:
    """``verdict='block'`` AND no break-glass override; warnings excluded."""
    if event.get("verdict") != "block":
        return False
    return not event.get("override_reason")


def _is_llm01(event: dict) -> bool:
    """Prompt-injection signal: ``escape_hatch`` set OR ``bash_pattern_kind`` set.

    Per design.md decision D8 (post-correction): the rule-event/v2 schema does
    not carry a ``cmd_injection`` value in ``block_class``; the closed
    ``bash_pattern_kind`` enum captures every Bash-injection pattern the L1
    hook blocks, so any non-empty value counts as LLM01 evidence.
    """
    if event.get("escape_hatch"):
        return True
    return bool(event.get("bash_pattern_kind"))


def _compute_hero(events: Iterable[dict]) -> dict[str, int]:
    incidents = 0
    injection = 0
    for ev in events:
        if _is_hero_incident(ev):
            incidents += 1
            if _is_llm01(ev):
                injection += 1
    return {
        "incidents_prevented_7d": incidents,
        "prompt_injection_blocks": injection,
    }


def _health_emoji(obey_rate: float) -> str:
    if obey_rate >= HEALTH_GREEN_FLOOR:
        return "green"
    if obey_rate >= HEALTH_YELLOW_FLOOR:
        return "yellow"
    return "red"


def _compute_obey_rate(events: list[dict]) -> float:
    if not events:
        return 0.0
    allowed = sum(1 for ev in events if ev.get("verdict") in {"allow", "warn"})
    return allowed / len(events)


def _compute_trend(
    events: list[dict],
    window_start: _dt.datetime,
    window_end: _dt.datetime,
) -> list[dict[str, Any]]:
    """Per-day buckets across the window."""
    by_day: dict[str, list[dict]] = defaultdict(list)
    for ev in events:
        ts = ev.get("timestamp")
        if not isinstance(ts, str):
            continue
        try:
            dt = _dt.datetime.fromisoformat(ts.replace("Z", "+00:00"))
        except ValueError:
            continue
        iso_day = dt.date().isoformat()
        by_day[iso_day].append(ev)

    points: list[dict[str, Any]] = []
    cursor = window_start.date()
    last_day = window_end.date()
    while cursor <= last_day:
        iso_day = cursor.isoformat()
        bucket = by_day.get(iso_day, [])
        rate = _compute_obey_rate(bucket) if bucket else 0.0
        points.append(
            {
                "iso_day": iso_day,
                "obey_rate": round(rate, 4),
                "events": len(bucket),
            }
        )
        cursor += _dt.timedelta(days=1)
    return points


def _compute_matrix(
    events: list[dict],
    prior_events: list[dict],
) -> list[dict[str, Any]]:
    """Rule × LLM agreement, with drift_flag in two senses."""
    # Current window: per-(slug, llm) obey-rate.
    cur_counts: dict[tuple[str, str], list[int]] = defaultdict(lambda: [0, 0])  # [n_allow_or_warn, n_total]
    for ev in events:
        slug = ev.get("slug")
        llm = ev.get("llm")
        if not slug or not llm:
            continue
        cur_counts[(slug, llm)][1] += 1
        if ev.get("verdict") in {"allow", "warn"}:
            cur_counts[(slug, llm)][0] += 1

    prior_counts: dict[tuple[str, str], list[int]] = defaultdict(lambda: [0, 0])
    for ev in prior_events:
        slug = ev.get("slug")
        llm = ev.get("llm")
        if not slug or not llm:
            continue
        prior_counts[(slug, llm)][1] += 1
        if ev.get("verdict") in {"allow", "warn"}:
            prior_counts[(slug, llm)][0] += 1

    # Build per-slug rows.
    slugs = sorted({k[0] for k in cur_counts})
    rows: list[dict[str, Any]] = []
    for slug in slugs:
        by_llm: dict[str, float] = {}
        slug_total = 0
        for (s, llm), (good, total) in cur_counts.items():
            if s != slug or total == 0:
                continue
            by_llm[llm] = round(good / total, 4)
            slug_total += total

        if not by_llm:
            continue

        # Drift sense 1: cross-LLM disagreement.
        cross_drift = (
            (max(by_llm.values()) - min(by_llm.values())) > CROSS_LLM_DRIFT_THRESHOLD
            if len(by_llm) >= 2
            else False
        )

        # Drift sense 2: per-LLM time-over-time, against prior window.
        time_drift = False
        for llm, rate_now in by_llm.items():
            good_p, total_p = prior_counts.get((slug, llm), [0, 0])
            if total_p == 0:
                continue
            rate_prior = good_p / total_p
            if abs(rate_now - rate_prior) > TIME_OVER_TIME_DRIFT_THRESHOLD:
                time_drift = True
                break

        # Suppress drift signalling on under-sampled rows.
        if slug_total < MATRIX_DRIFT_MIN_EVENTS:
            cross_drift = False
            time_drift = False

        if cross_drift and time_drift:
            flag = "both"
        elif cross_drift:
            flag = "cross_llm"
        elif time_drift:
            flag = "time_over_time"
        else:
            flag = "none"

        rows.append(
            {
                "rule_slug": slug,
                "by_llm": by_llm,
                "drift_flag": flag,
            }
        )
    return rows


def _compute_honesty(events: list[dict]) -> list[dict[str, Any]]:
    """Self_check ↔ verdict agreement per LLM.

    Denominator (design.md Q2 closed here): events where a verdict was produced
    (allow / block / warn). Since verdict is a required field in rule-event/v2,
    that is every well-formed event.

    Agreement: ``self_check == (verdict == "allow")``. The LLM correctly reports
    rule-following when it claims it followed and the hook saw allow; correctly
    reports breaking when it claims it broke and the hook saw block or warn.
    """
    per_llm: dict[str, list[int]] = defaultdict(lambda: [0, 0])  # [agreements, total]
    for ev in events:
        llm = ev.get("llm")
        if not llm:
            continue
        verdict = ev.get("verdict")
        if verdict not in {"allow", "block", "warn"}:
            continue
        self_check = bool(ev.get("self_check"))
        claimed_followed = self_check
        actually_followed = verdict == "allow"
        per_llm[llm][1] += 1
        if claimed_followed == actually_followed:
            per_llm[llm][0] += 1

    rows: list[dict[str, Any]] = []
    for llm in sorted(per_llm):
        agree, total = per_llm[llm]
        if total < HONESTY_MIN_EVENTS:
            # Suppress under-sampled rows; do not fabricate signal.
            continue
        rows.append(
            {
                "llm": llm,
                "self_check_verdict_agreement_rate": round(agree / total, 4),
                "n_events": total,
            }
        )
    return rows


def _compute_friction(events: list[dict]) -> list[dict[str, Any]]:
    by_slug_override: dict[str, list[str]] = defaultdict(list)
    by_slug_count: Counter[str] = Counter()
    for ev in events:
        if ev.get("verdict") != "block":
            continue
        reason = ev.get("override_reason")
        if not reason:
            continue
        slug = ev.get("slug")
        if not slug:
            continue
        by_slug_count[slug] += 1
        by_slug_override[slug].append(reason)

    rows: list[dict[str, Any]] = []
    for slug, count in by_slug_count.most_common(FRICTION_TOP_RULES):
        top_reasons = [r for r, _ in Counter(by_slug_override[slug]).most_common(FRICTION_TOP_REASONS)]
        rows.append(
            {
                "rule_slug": slug,
                "break_glass_count": count,
                "override_reasons_top": top_reasons,
            }
        )
    return rows


# ---------------------------------------------------------------------------
# Caveman panel.
# ---------------------------------------------------------------------------


def _read_caveman_json(consumer_root: Path) -> dict | None:
    p = consumer_root / ".ai-playbook" / "caveman.json"
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _resolve_caveman_state(consumer_root: Path) -> str:
    state = _read_caveman_json(consumer_root)
    if state is None:
        return "missing"
    if state.get("enabled"):
        return "on"
    return "off"


def _invoke_caveman_stats(consumer_root: Path, quiet: bool) -> dict | None:
    """Best-effort: invoke caveman stats and return the dict, else None."""
    try:
        from scripts.caveman import stats as caveman_stats  # type: ignore
    except Exception:
        caveman_stats = None  # type: ignore

    if caveman_stats is None:
        # Fall back to subprocess (handles cases where caveman is dynamically reloaded).
        try:
            result = subprocess.run(
                [sys.executable, "-m", "scripts.caveman.stats", "--json"],
                capture_output=True,
                text=True,
                timeout=20,
                cwd=consumer_root,
            )
            if result.returncode != 0:
                return None
            return json.loads(result.stdout)
        except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError):
            return None

    try:
        session_stats = caveman_stats.collect_stats(consumer_root)
        saved = caveman_stats.extrapolated_savings(session_stats.output_tokens)
        cost_saved = (saved / 1_000_000.0) * caveman_stats.COST_PER_M_OUTPUT_USD
    except Exception:  # noqa: BLE001 — caveman is best-effort.
        return None

    state = _read_caveman_json(consumer_root) or {}
    return {
        "mode": state.get("mode", "ultra"),
        "components": state.get("components") or {},
        "activation_rate": 0.0 if session_stats.sessions == 0 else 1.0,
        "tokens_in_total": session_stats.input_tokens,
        "tokens_out_total": session_stats.output_tokens,
        "tokens_in_delta": 0,
        "tokens_out_delta": -saved,
        "cost_saved_usd": round(cost_saved, 2),
    }


def _compute_caveman_panel(consumer_root: Path, quiet: bool) -> tuple[str, dict]:
    state = _resolve_caveman_state(consumer_root)
    if state != "on":
        return state, {"state": state}

    raw = _invoke_caveman_stats(consumer_root, quiet=quiet)
    if not raw:
        # Treat invocation failure as missing — better than silently fabricating data.
        return "missing", {"state": "missing"}

    panel = {
        "activation_rate": float(raw.get("activation_rate", 0.0)),
        "mode": raw.get("mode", "ultra"),
        "components": {k: bool(v) for k, v in (raw.get("components") or {}).items()},
        "tokens_in_delta": int(raw.get("tokens_in_delta", 0)),
        "tokens_out_delta": int(raw.get("tokens_out_delta", 0)),
        "cost_saved_usd": float(raw.get("cost_saved_usd", 0.0)),
    }
    return state, panel


# ---------------------------------------------------------------------------
# Ponytail panel (rung-1: count of `ponytail:` simplification markers).
#
# Caveman's twin measures a different axis: caveman saves output tokens (a
# physical quantity); ponytail records *cuts taken* — the `ponytail:` markers
# skills/ponytail-debt harvests. We show a count, not a dollar figure, because
# the savings are real but not LLM-self-reported here. Cost extrapolation and a
# considered-vs-built ratio are deferred (rung 2).
# ---------------------------------------------------------------------------


def _read_ponytail_json(consumer_root: Path) -> dict | None:
    p = consumer_root / ".ai-playbook" / "ponytail.json"
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _resolve_ponytail_state(consumer_root: Path) -> str:
    state = _read_ponytail_json(consumer_root)
    if state is None:
        return "missing"
    if state.get("enabled"):
        return "on"
    return "off"


def _compute_ponytail_panel(consumer_root: Path, since_iso: str) -> tuple[str, dict]:
    state = _resolve_ponytail_state(consumer_root)
    if state != "on":
        return state, {"state": state}

    try:
        from scripts.ponytail import stats as ponytail_stats  # type: ignore

        scan = ponytail_stats.collect(consumer_root, since_iso=since_iso)
    except Exception:  # noqa: BLE001 — ponytail stats is best-effort.
        # Treat scan failure as missing — better than fabricating a count.
        return "missing", {"state": "missing"}

    raw = _read_ponytail_json(consumer_root) or {}
    panel = {
        "markers": int(scan.get("markers", 0)),
        "mode": raw.get("mode", "ultra"),
        "components": {k: bool(v) for k, v in (raw.get("components") or {}).items()},
    }
    # markers_window (cuts taken in the window, via git) is omitted when git
    # can't answer — never faked to 0.
    if "markers_window" in scan:
        panel["markers_window"] = int(scan["markers_window"])
    return state, panel


# ---------------------------------------------------------------------------
# Top-level pipeline.
# ---------------------------------------------------------------------------


def _scrub_event_inplace(event: dict) -> dict:
    """Apply the second-line privacy guards expected by the spec."""
    if "target_rel" in event:
        scrubbed = _scrub_target_rel(event.get("target_rel"))
        if scrubbed is None:
            event.pop("target_rel", None)
        else:
            event["target_rel"] = scrubbed
    # Raw Bash commands must never appear; rule-event/v2 doesn't carry them,
    # but defensively drop any unexpected ``bash_command`` field.
    event.pop("bash_command", None)
    return event


def build_payload(
    consumer_root: Path,
    state_dir: Path | None,
    window_days: int,
    pricing_path: Path,
    empty_state_threshold: int,
    *,
    quiet: bool = False,
) -> dict:
    state_dir_resolved = _resolve_state_dir(state_dir, consumer_root)
    events_path = state_dir_resolved / "rule-events.jsonl"
    parsed = _iter_jsonl(events_path)

    now = _utcnow()
    window_start = now - _dt.timedelta(days=window_days)
    prior_start = window_start - _dt.timedelta(days=window_days)

    in_window: list[dict] = []
    in_prior: list[dict] = []
    for raw in parsed.events:
        ev = _scrub_event_inplace(dict(raw))
        if _within_window(ev, window_start, now):
            in_window.append(ev)
        elif _within_window(ev, prior_start, window_start):
            in_prior.append(ev)

    events_seen = len(in_window)
    events_skipped = parsed.events_skipped

    pricing_sha = _sha256_of_file(pricing_path) or ("0" * 64)

    payload: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": _iso(now),
        "pricing_version": pricing_sha,
        "window": {
            "days": window_days,
            "from_iso": _iso(window_start),
            "to_iso": _iso(now),
            "events_seen": events_seen,
            "events_skipped": events_skipped,
        },
        "empty_state_threshold": empty_state_threshold,
    }

    caveman_state, caveman_panel = _compute_caveman_panel(consumer_root, quiet=quiet)
    payload["caveman_state"] = caveman_state

    ponytail_state, ponytail_panel = _compute_ponytail_panel(consumer_root, _iso(window_start))
    payload["ponytail_state"] = ponytail_state

    if events_seen < empty_state_threshold:
        # Empty-state branch: emit zero-filled panel scaffolds so the renderer
        # has a consistent shape; the renderer suppresses contents itself.
        payload["panels"] = {
            "hero": {"incidents_prevented_7d": 0, "prompt_injection_blocks": 0},
            "secondary": {
                "obey_rate_7d": 0.0,
                "cost_saved_usd": {"value": 0.0, "methodology": COST_METHODOLOGY_URL},
                "health_emoji": "red",
            },
            "trend": {"points": []},
            "matrix": {"rows": []},
            "honesty": {"rows": []},
            "friction": {"rows": []},
            "caveman": caveman_panel,
            "ponytail": ponytail_panel,
        }
        return payload

    hero = _compute_hero(in_window)
    obey_rate = round(_compute_obey_rate(in_window), 4)
    cost_value = float(caveman_panel.get("cost_saved_usd", 0.0)) if caveman_state == "on" else 0.0

    payload["panels"] = {
        "hero": hero,
        "secondary": {
            "obey_rate_7d": obey_rate,
            "cost_saved_usd": {
                "value": round(cost_value, 2),
                "methodology": COST_METHODOLOGY_URL,
            },
            "health_emoji": _health_emoji(obey_rate),
        },
        "trend": {"points": _compute_trend(in_window, window_start, now)},
        "matrix": {"rows": _compute_matrix(in_window, in_prior)},
        "honesty": {"rows": _compute_honesty(in_window)},
        "friction": {"rows": _compute_friction(in_window)},
        "caveman": caveman_panel,
        "ponytail": ponytail_panel,
    }
    return payload


def _validate_against_schema(payload: dict, schema_path: Path) -> list[str]:
    try:
        import jsonschema  # type: ignore
    except ImportError:
        return []  # Validation is best-effort if jsonschema is not installed.

    try:
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"schema load failed: {exc}"]

    v = jsonschema.Draft202012Validator(schema)
    return [
        f"{'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
        for err in v.iter_errors(payload)
    ]


def _render_sidecar_js(payload: dict) -> str:
    body = json.dumps(payload, indent=2, sort_keys=True)
    return _JS_HEADER + _JS_PREFIX + body + _JS_SUFFIX


# ---------------------------------------------------------------------------
# CLI.
# ---------------------------------------------------------------------------


def _parse_window(value: str) -> int:
    value = value.strip().lower()
    if value in {"7", "7d", "7days"}:
        return 7
    if value in {"30", "30d", "30days"}:
        return 30
    raise argparse.ArgumentTypeError("window must be one of: 7d, 30d")


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m scripts.telemetry.build_dashboard_data",
        description="Build the dashboard-data/v1 sidecar from local telemetry.",
    )
    parser.add_argument(
        "--window",
        type=_parse_window,
        default=7,
        help="Aggregation window in days. Allowed values: 7d, 30d. Default: 7d.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output sidecar path. Default: "
            "<consumer-root>/.ai-playbook/dashboard-data.js."
        ),
    )
    parser.add_argument(
        "--consumer-root",
        type=Path,
        default=None,
        help="Consumer repo root. Default: current working directory.",
    )
    parser.add_argument(
        "--state-dir",
        type=Path,
        default=None,
        help=(
            "Override the telemetry state directory. Default: "
            "$AI_PLAYBOOK_STATE_DIR or <consumer-root>/.ai-playbook-state/."
        ),
    )
    parser.add_argument(
        "--pricing-path",
        type=Path,
        default=None,
        help="Path to pricing.yaml. Default: <playbook>/configs/pricing.yaml.",
    )
    parser.add_argument(
        "--schema-path",
        type=Path,
        default=None,
        help=(
            "Path to the dashboard-data/v1 JSON schema. Default: "
            "<playbook>/schemas/schema-dashboard-data-v1.json."
        ),
    )
    parser.add_argument(
        "--empty-state-threshold",
        type=int,
        default=DEFAULT_EMPTY_STATE_THRESHOLD,
        help="Threshold below which the renderer shows the empty state.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress informational stdout messages.",
    )
    parser.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip JSON schema validation of the output payload (not recommended).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_arg_parser().parse_args(argv)

    consumer_root = (args.consumer_root or _default_consumer_root()).resolve()
    output_path = (args.output or _default_output(consumer_root)).resolve()

    here = Path(__file__).resolve()
    playbook_root = here.parent.parent.parent  # scripts/telemetry/build_dashboard_data.py → playbook root

    pricing_path = (args.pricing_path or (playbook_root / "configs" / "pricing.yaml")).resolve()
    schema_path = (args.schema_path or (playbook_root / "schemas" / "schema-dashboard-data-v1.json")).resolve()

    payload = build_payload(
        consumer_root=consumer_root,
        state_dir=args.state_dir,
        window_days=args.window,
        pricing_path=pricing_path,
        empty_state_threshold=args.empty_state_threshold,
        quiet=args.quiet,
    )

    if not args.no_validate:
        errors = _validate_against_schema(payload, schema_path)
        if errors:
            print("dashboard-data payload failed schema validation:", file=sys.stderr)
            for err in errors[:20]:
                print(f"  - {err}", file=sys.stderr)
            return 2

    _atomic_write(output_path, _render_sidecar_js(payload))

    if not args.quiet:
        ev = payload["window"]
        print(
            f"build_dashboard_data: wrote {output_path} "
            f"(window={args.window}d, events_seen={ev['events_seen']}, "
            f"events_skipped={ev['events_skipped']}, "
            f"caveman_state={payload['caveman_state']})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
