"""GPLO-1378: real negative guardrail events reach both Dashboard panels."""

from __future__ import annotations

import ast
import importlib.util
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from scripts import hook_dispatcher, sweep_execute, sweep_scan  # noqa: E402
from scripts.rules import _telemetry  # noqa: E402
from scripts.telemetry import build_dashboard_data as dashboard  # noqa: E402

AUDITED = {
    "sweep-scan": ("audit-sweep-scan", "script", "warn"),
    "sweep-execute": ("audit-sweep-execute", "script", "warn"),
    "repo-hygiene": ("audit-repo-hygiene", "rule", "block"),
    "capability-wiring": ("audit-capability-wiring", "rule", "block"),
    "cleanup-zombies": ("audit-cleanup-zombies", "rule", "warn"),
    "jira-ticket-standard": ("claude", None, "block"),
}
EVENTS_PER_GUARDRAIL = dashboard.HONESTY_MIN_EVENTS


def _load_rule(filename: str):
    path = ROOT / "scripts" / "rules" / filename
    name = "audit_" + filename.replace(".", "_").replace("-", "_")
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _write_yaml(path: Path, payload: dict) -> Path:
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return path


def _negative_inputs(tmp_path: Path) -> dict[str, tuple[object, list[str], int]]:
    repo = tmp_path / "repo"
    (repo / "src").mkdir(parents=True)
    (repo / "src" / "alpha.py").write_text("def run(): ...\n", encoding="utf-8")
    (repo / "src" / "beta.py").write_text("def run(): ...\n", encoding="utf-8")
    (repo / "registry.py").write_text('ROUTES = {"alpha": 1}\n', encoding="utf-8")
    (repo / "requirements.txt").write_text("leftpad==1.0\n", encoding="utf-8")

    wiring_config = _write_yaml(
        repo / "wiring.yaml",
        {
            "schema": "ai-playbook/wiring-assertions/v1",
            "schema_version": "1.0.0",
            "root": ".",
            "assertions": [
                {
                    "id": "audit-registration",
                    "description": "every source module is registered",
                    "every": "src/*.py",
                    "referenced_in": "registry.py",
                    "by": '"{stem}"\\s*:',
                    "severity": "S1",
                }
            ],
        },
    )
    hygiene_config = _write_yaml(
        repo / "repo-hygiene.yaml",
        {
            "schema": "ai-playbook/repo-hygiene/v1",
            "schema_version": "1.0.0",
            "root": ".",
            "dependencies": [
                {
                    "id": "audit-dependencies",
                    "description": "every dependency is used",
                    "manifest": "requirements.txt",
                    "format": "requirements-txt",
                    "severity": "S1",
                    "status": "enforced",
                    "channels": [
                        {
                            "id": "python-import",
                            "kind": "import",
                            "language": "python",
                            "corpus": "src/**/*.py",
                        }
                    ],
                }
            ],
            "artifacts": [],
        },
    )
    malformed = tmp_path / "malformed.yaml"
    malformed.write_text("not: [valid\n", encoding="utf-8")
    missing_ledger = tmp_path / "missing-ledger.json"

    return {
        "sweep-scan": (sweep_scan.main, ["validate", "--config", str(malformed)], 2),
        "sweep-execute": (
            sweep_execute.main,
            ["--root", str(repo), "plan", "--ledger", str(missing_ledger)],
            2,
        ),
        "repo-hygiene": (
            _load_rule("repo-hygiene.rule.py").main,
            ["check", "--config", str(hygiene_config)],
            1,
        ),
        "capability-wiring": (
            _load_rule("capability-wiring.rule.py").main,
            ["check", "--config", str(wiring_config)],
            1,
        ),
        "cleanup-zombies": (
            _load_rule("cleanup-zombies.rule.py").main,
            ["--manifest", str(malformed), "validate"],
            2,
        ),
    }


def _read_sidecar(path: Path) -> dict:
    prefix = "window.DASHBOARD_DATA = "
    text = path.read_text(encoding="utf-8")
    assert text.startswith("// generated by")
    payload = text[text.index(prefix) + len(prefix):].strip()
    assert payload.endswith(";")
    return json.loads(payload[:-1])


def test_real_negative_events_render_in_matrix_and_honesty(tmp_path, monkeypatch) -> None:
    consumer = tmp_path / "consumer"
    state_dir = consumer / ".ai-playbook-state"
    state_dir.mkdir(parents=True)
    (consumer / ".ai-playbook").mkdir()
    monkeypatch.setenv("AI_PLAYBOOK_STATE_DIR", str(state_dir))
    monkeypatch.setenv("AI_PLAYBOOK_SESSION_ID", "gplo-1378-negative-control")
    monkeypatch.setenv("AI_PLAYBOOK_HOOK_TRIGGER", "test:negative-control")

    negative_inputs = _negative_inputs(tmp_path)
    for slug, (llm, kind, _expected_verdict) in AUDITED.items():
        monkeypatch.setenv("AI_PLAYBOOK_LLM", llm)
        if slug == "jira-ticket-standard":
            rule = next(rule for rule in hook_dispatcher.load_rules(ROOT) if rule.slug == slug)
            event = {
                "tool_name": "mcp__claude_ai_Atlassian__createJiraIssue",
                "tool_input": {
                    "issueTypeName": "Bug",
                    "description": "Se rompe algo.",
                },
                "model": llm,
                "session_id": "gplo-1378-negative-control",
            }
            for _ in range(EVENTS_PER_GUARDRAIL):
                blocked, _, fired = hook_dispatcher.run_rules(
                    [rule], "PreToolUse", event, consumer_root=consumer
                )
                assert blocked is True
                assert fired == [slug]
            continue

        main_fn, argv, expected_rc = negative_inputs[slug]
        emit = _telemetry.script_emit if kind == "script" else _telemetry.cli_emit
        for _ in range(EVENTS_PER_GUARDRAIL):
            assert emit(slug, main_fn, argv) == expected_rc

    events = [
        json.loads(line)
        for line in (state_dir / "rule-events.jsonl").read_text(encoding="utf-8").splitlines()
    ]
    assert len(events) == len(AUDITED) * EVENTS_PER_GUARDRAIL
    for slug, (llm, kind, expected_verdict) in AUDITED.items():
        matching = [event for event in events if event["slug"] == slug]
        assert len(matching) == EVENTS_PER_GUARDRAIL
        assert {event["schema"] for event in matching} == {"rule-event/v2"}
        assert {event["verdict"] for event in matching} == {expected_verdict}
        assert {event["llm"] for event in matching} == {llm}
        if kind is not None:
            assert {event["kind"] for event in matching} == {kind}

    output = tmp_path / "dashboard-data.js"
    rc = dashboard.main(
        [
            "--consumer-root",
            str(consumer),
            "--window",
            "7d",
            "--output",
            str(output),
            "--empty-state-threshold",
            "1",
            "--pricing-path",
            str(ROOT / "configs" / "pricing.yaml"),
            "--schema-path",
            str(ROOT / "schemas" / "schema-dashboard-data-v1.json"),
            "--quiet",
        ]
    )
    assert rc == 0
    panels = _read_sidecar(output)["panels"]
    matrix = {row["rule_slug"]: row for row in panels["matrix"]["rows"]}
    honesty = {row["llm"]: row for row in panels["honesty"]["rows"]}

    for slug, (llm, _, _) in AUDITED.items():
        assert llm in matrix[slug]["by_llm"], f"{slug} missing from matrix rendering"
        assert honesty[llm]["n_events"] == EVENTS_PER_GUARDRAIL
        assert honesty[llm]["self_check_verdict_agreement_rate"] == 1.0


def _main_guards(tree: ast.Module) -> list[ast.If]:
    """Return every module-level ``if __name__ == "__main__":`` block.

    Scoping the `cli_emit` check to these nodes (rather than `ast.walk(tree)`
    over the whole module) matters: a bare whole-file walk would accept a
    `cli_emit(...)` call sitting in unrelated or unreachable code — a dead
    branch, an unused helper, a docstring-turned-code snippet — as if it were
    the script's real CLI entrypoint. Some rule files legitimately split this
    guard in two (an early one that only does `sys.path.insert` bootstrap, a
    later one that dispatches `cli_emit`), so every guard at module level is
    collected rather than returning on the first match.
    """
    guards = []
    for node in tree.body:
        if not isinstance(node, ast.If):
            continue
        test = node.test
        if (
            isinstance(test, ast.Compare)
            and isinstance(test.left, ast.Name)
            and test.left.id == "__name__"
            and len(test.comparators) == 1
            and isinstance(test.comparators[0], ast.Constant)
            and test.comparators[0].value == "__main__"
        ):
            guards.append(node)
    return guards


def test_every_rule_imports_the_direct_telemetry_wrapper() -> None:
    # The spec (ci-guardrail-audit-evidence §"Every playbook `.rule.py` SHALL
    # import and invoke the direct `_telemetry` wrapper") requires BOTH
    # halves. Checking only the import lets a rule that imports `cli_emit`
    # but never calls it (e.g. a stray `__main__` that calls `main()`
    # directly) pass silently, so both are asserted per file.
    silent: list[str] = []
    uninvoked: list[str] = []
    for path in sorted((ROOT / "scripts" / "rules").glob("*.rule.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        direct_wrapper = any(
            isinstance(node, ast.ImportFrom)
            and node.module == "scripts.rules._telemetry"
            and any(alias.name == "cli_emit" for alias in node.names)
            for node in ast.walk(tree)
        )
        if not direct_wrapper:
            silent.append(path.name)

        guards = _main_guards(tree)
        invokes_cli_emit = any(
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "cli_emit"
            for guard in guards
            for node in ast.walk(guard)
        )
        if not invokes_cli_emit:
            uninvoked.append(path.name)

    assert not silent, f"rule scripts without a direct `cli_emit` import: {silent}"
    assert not uninvoked, (
        f"rule scripts whose `if __name__ == '__main__':` block(s) do not "
        f"invoke `cli_emit`: {uninvoked}"
    )
    dispatcher_source = (ROOT / "scripts" / "hook_dispatcher.py").read_text(encoding="utf-8")
    assert "_emit_run_event(r.slug, verdict.verdict" in dispatcher_source


def test_main_guard_ast_check_rejects_an_unreachable_cli_emit_call() -> None:
    """Direct proof the `_main_guards` scoping actually matters.

    A file with `cli_emit` called only in dead/unrelated code (never inside
    `if __name__ == "__main__":`) must be classified as NOT invoking it — a
    bare whole-file `ast.walk` would wrongly accept this.
    """
    unreachable_source = (
        "from scripts.rules._telemetry import cli_emit\n"
        "\n"
        "def _dead_helper():\n"
        "    # never called by anything, and not inside a __main__ guard\n"
        "    return cli_emit('not-really-the-entrypoint', lambda a: 0)\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    raise SystemExit(main(None))\n"
    )
    tree = ast.parse(unreachable_source, filename="synthetic.rule.py")
    guards = _main_guards(tree)
    assert len(guards) == 1
    invokes_cli_emit = any(
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "cli_emit"
        for guard in guards
        for node in ast.walk(guard)
    )
    assert invokes_cli_emit is False, (
        "an unreachable cli_emit call outside the __main__ guard must not "
        "count as invocation"
    )

    # And the positive control: moving the same call inside the guard flips it.
    reachable_source = (
        "from scripts.rules._telemetry import cli_emit\n"
        "\n"
        "if __name__ == '__main__':\n"
        "    raise SystemExit(cli_emit('real-slug', main))\n"
    )
    tree2 = ast.parse(reachable_source, filename="synthetic.rule.py")
    guards2 = _main_guards(tree2)
    assert any(
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id == "cli_emit"
        for guard in guards2
        for node in ast.walk(guard)
    )


def test_audited_direct_scripts_remain_wrapped_by_script_emit() -> None:
    for relative in ("scripts/sweep_scan.py", "scripts/sweep_execute.py"):
        tree = ast.parse((ROOT / relative).read_text(encoding="utf-8"), filename=relative)
        imports_script_emit = any(
            isinstance(node, ast.ImportFrom)
            and node.module == "scripts.rules._telemetry"
            and any(alias.name == "script_emit" for alias in node.names)
            for node in ast.walk(tree)
        )
        calls_script_emit = any(
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "script_emit"
            for node in ast.walk(tree)
        )
        assert imports_script_emit and calls_script_emit, f"{relative} bypasses script telemetry"
