"""Apply an ``ai-playbook-config/v1`` bundle JSON to a consumer project.

Bundle exported by ``tools/config-ui/index.html`` (HTML UI) lands here. The
script projects each section to its on-disk representation:

    rules{}            → <target>/.ai-playbook/rules-toggle.json (direct write)
    features.caveman   → subprocess: python -m scripts.caveman on/off ...
    global_flags{}     → <target>/.ai-playbook/feature-flags.env (marker block)

Per-rule ``advanced{}`` sub-toggles (e.g. ``apply-skill-enforcement.advanced.bash_inspection``)
also project to the env file via the rules-inventory mapping. The L1 hook keeps
reading the env var as before; the bundle is just the declarative source.

Per the schema literal in ``schema-caveman-toggle-v1.json``:

> UI consumers MUST go through the CLI (python -m scripts.caveman) rather
> than touching the file directly.

So we subprocess. The caveman CLI handles backups, materialisation of the
AGENTS.md auto-managed block, and MCP wrapping — none of which we want to
re-implement.

Policy on errors: **best-effort per section**. A failure in one section is
reported in the audit log + the result, but the other sections still run.
Exit code is 0 if all sections succeeded, 1 if any failed.

CLI
---
    python -m scripts.apply_config <bundle.json> [--target PATH] [--dry-run] [--json]

Exit codes
----------
    0   all sections applied successfully (no-op sections count as success)
    1   one or more sections failed; see report
    2   environment/setup error (schema missing, jsonschema absent, ...)
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

try:
    import jsonschema
except ImportError:
    print(
        "❌ jsonschema is required for scripts.apply_config. "
        "Install with: pip install jsonschema",
        file=sys.stderr,
    )
    raise SystemExit(2) from None

from scripts import rules_toggle  # noqa: E402

STATE_DIR_NAME = ".ai-playbook"
FEATURE_FLAGS_FILENAME = "feature-flags.env"
AUDIT_FILENAME = rules_toggle.AUDIT_FILENAME
APPLIED_BUNDLE_FILENAME = "applied-config.json"
APPLIED_BUNDLE_JS_FILENAME = "applied-config.js"
ENV_MARKER_BEGIN = "# >>> ai-playbook-config: generated by apply_config — DO NOT EDIT MANUALLY >>>"
ENV_MARKER_END = "# <<< ai-playbook-config <<<"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@dataclass
class SectionResult:
    name: str
    ok: bool
    detail: str = ""
    changes: list[str] = field(default_factory=list)


@dataclass
class ApplyReport:
    target: Path
    bundle_path: Path
    sections: list[SectionResult] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return all(s.ok for s in self.sections)

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "target": self.target.as_posix(),
            "bundle_path": self.bundle_path.as_posix(),
            "sections": [
                {"name": s.name, "ok": s.ok, "detail": s.detail, "changes": s.changes}
                for s in self.sections
            ],
        }

    def to_markdown(self) -> str:
        lines = [f"# apply_config report", f"- target: `{self.target}`", f"- bundle: `{self.bundle_path}`", ""]
        for s in self.sections:
            sig = "✅" if s.ok else "❌"
            lines.append(f"## {sig} {s.name}")
            if s.detail:
                lines.append(s.detail)
            for c in s.changes:
                lines.append(f"- {c}")
            lines.append("")
        return "\n".join(lines)


def _load_bundle_schema() -> dict[str, Any]:
    root = rules_toggle.find_playbook_root()
    if root is None:
        raise FileNotFoundError(
            "ai-playbook root not found (need specs/ + scripts/ + schemas/ on parent chain)."
        )
    p = root / "schemas" / "schema-ai-playbook-config-v1.json"
    if not p.is_file():
        raise FileNotFoundError(f"Schema not found: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _load_inventory(name: str) -> dict[str, Any] | None:
    """Load a tools/config-ui/<name>-inventory.json file. Returns None if missing."""
    root = rules_toggle.find_playbook_root()
    if root is None:
        return None
    p = root / "tools" / "config-ui" / name
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _audit_append(target: Path, entry: dict[str, Any]) -> None:
    p = target / STATE_DIR_NAME / AUDIT_FILENAME
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False, sort_keys=True) + "\n")
    except OSError:
        pass


def _actor() -> str:
    return os.environ.get("USER") or os.environ.get("USERNAME") or "unknown"


# ---------------------------------------------------------------------------
# Section 1: rules
# ---------------------------------------------------------------------------


def apply_rules(target: Path, bundle: dict[str, Any], rules_inventory: dict[str, Any] | None) -> tuple[SectionResult, dict[str, str]]:
    """Write rules-toggle.json + return env var entries derived from advanced{}.

    Returns (SectionResult, env_entries) where env_entries is a dict of
    {ENV_VAR: VALUE} to be merged into feature-flags.env by the global-flags
    section. Empty dict if no advanced sub-toggles diverged from defaults.
    """
    sr = SectionResult(name="rules", ok=True)
    rules = bundle.get("rules") or {}
    env_entries: dict[str, str] = {}

    if not rules:
        sr.detail = "no rules in bundle — no-op"
        return sr, env_entries

    # Build the state file dict.
    state = rules_toggle.default_state()
    state["rules"] = {}
    state["applied_at"] = datetime.now(UTC).isoformat()
    state["applied_by"] = _actor()

    for slug, entry in rules.items():
        if not isinstance(entry, dict):
            sr.ok = False
            sr.detail = f"rule {slug!r} is not a dict"
            return sr, env_entries
        state["rules"][slug] = dict(entry)
        sr.changes.append(f"{slug}: {('OFF' if entry.get('enabled') is False else 'partial')}")

    try:
        rules_toggle.write_state(target, state)
    except Exception as e:  # noqa: BLE001 — surface to report
        sr.ok = False
        sr.detail = f"failed to write rules-toggle.json: {e}"
        return sr, env_entries
    sr.changes.append(f"wrote {rules_toggle.state_path(target)}")

    # Derive env entries from advanced{} via inventory mapping.
    if rules_inventory is not None:
        inv_by_slug = {r["slug"]: r for r in rules_inventory.get("rules", [])}
        for slug, entry in rules.items():
            advanced = entry.get("advanced") or {}
            inv_rule = inv_by_slug.get(slug)
            if not inv_rule:
                continue
            for adv in inv_rule.get("advanced", []) or []:
                key = adv.get("key")
                if key is None or key not in advanced:
                    continue
                value = advanced[key]
                env_var = adv.get("env_var")
                if not env_var:
                    continue
                v_on = adv.get("value_on", "1")
                v_off = adv.get("value_off", "0")
                env_entries[env_var] = v_on if value else v_off

    return sr, env_entries


# ---------------------------------------------------------------------------
# Section 2: features.caveman (subprocess delegation)
# ---------------------------------------------------------------------------


def apply_caveman(target: Path, caveman_intent: dict[str, Any] | None, *, dry_run: bool = False) -> SectionResult:
    sr = SectionResult(name="features.caveman", ok=True)
    if not caveman_intent:
        sr.detail = "no caveman intent in bundle — no-op"
        return sr

    enabled = bool(caveman_intent.get("enabled"))
    mode = caveman_intent.get("mode", "full")
    components_dict = caveman_intent.get("components") or {}
    requested = [k for k, v in components_dict.items() if v]

    if dry_run:
        if enabled:
            sr.changes.append(f"DRY-RUN would invoke: python -m scripts.caveman on --mode {mode} --components {','.join(requested) or 'response_style'}")
        else:
            sr.changes.append("DRY-RUN would invoke: python -m scripts.caveman off")
        return sr

    if enabled:
        cmd = [sys.executable, "-m", "scripts.caveman", "on", "--mode", mode]
        if requested:
            cmd.extend(["--components", ",".join(requested)])
    else:
        cmd = [sys.executable, "-m", "scripts.caveman", "off"]

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(target),
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except OSError as e:
        sr.ok = False
        sr.detail = f"subprocess launch failed: {e}"
        return sr

    if proc.returncode != 0:
        sr.ok = False
        sr.detail = (
            f"caveman CLI exit {proc.returncode}\n"
            f"  stdout: {proc.stdout.strip()[:500]}\n"
            f"  stderr: {proc.stderr.strip()[:500]}"
        )
        return sr
    sr.changes.append(f"invoked: {' '.join(cmd)}")
    if proc.stdout.strip():
        sr.changes.append(f"caveman output: {proc.stdout.strip()[:300]}")
    return sr


# ---------------------------------------------------------------------------
# Section 3: global_flags (env file with marker block)
# ---------------------------------------------------------------------------


def apply_global_flags(
    target: Path,
    bundle: dict[str, Any],
    rules_env_entries: dict[str, str],
    global_flags_inventory: dict[str, Any] | None,
) -> SectionResult:
    sr = SectionResult(name="global_flags", ok=True)

    flag_intents = bundle.get("global_flags") or {}
    # Merge: rules-derived env entries come first (advanced sub-toggles), then
    # global_flags overlay on top (global wins on collision — unlikely but
    # explicit).
    env_entries: dict[str, str] = dict(rules_env_entries)

    if global_flags_inventory is not None:
        inv_by_key = {f["key"]: f for f in global_flags_inventory.get("flags", [])}
        for key, value in flag_intents.items():
            spec = inv_by_key.get(key)
            if spec is None:
                sr.changes.append(f"⚠ unknown global flag {key!r}; skipped")
                continue
            env_var = spec.get("env_var")
            if not env_var:
                continue
            v_on = spec.get("value_on", "1")
            v_off = spec.get("value_off", "")
            env_entries[env_var] = v_on if value else v_off

    if not env_entries and not flag_intents:
        sr.detail = "no global_flags or rules-derived env entries — no-op"
        return sr

    try:
        changes = _write_env_block(target, env_entries)
    except OSError as e:
        sr.ok = False
        sr.detail = f"failed to write feature-flags.env: {e}"
        return sr
    sr.changes.extend(changes)
    return sr


def _write_env_block(target: Path, env_entries: dict[str, str]) -> list[str]:
    """Write/update the marker block in <target>/.ai-playbook/feature-flags.env.

    Idempotent: if the file already contains the marker block, the block is
    replaced in place. If not, the block is appended (creating the file if
    needed). Lines outside the markers are preserved.

    Empty env_entries clears the block (writes the markers with no content
    inside, so future appends are still recognised).
    """
    p = target / STATE_DIR_NAME / FEATURE_FLAGS_FILENAME
    p.parent.mkdir(parents=True, exist_ok=True)

    if p.is_file():
        text = p.read_text(encoding="utf-8")
    else:
        text = ""

    lines = text.split("\n")
    begin_idx = end_idx = None
    for i, line in enumerate(lines):
        if line == ENV_MARKER_BEGIN and begin_idx is None:
            begin_idx = i
        elif line == ENV_MARKER_END and begin_idx is not None and end_idx is None:
            end_idx = i

    new_block = [ENV_MARKER_BEGIN]
    for k in sorted(env_entries):
        v = env_entries[k]
        new_block.append(f"{k}={v}")
    new_block.append(ENV_MARKER_END)

    changes: list[str] = []
    if begin_idx is not None and end_idx is not None:
        # Replace existing block.
        new_lines = lines[:begin_idx] + new_block + lines[end_idx + 1:]
        changes.append(f"replaced env block ({end_idx - begin_idx - 1} → {len(env_entries)} entries)")
    else:
        # Append new block. Ensure single blank line separator if text exists.
        existing = [ln for ln in lines if ln.strip() != ""]
        new_lines = list(existing)
        if new_lines:
            new_lines.append("")
        new_lines.extend(new_block)
        new_lines.append("")
        changes.append(f"appended new env block ({len(env_entries)} entries) to {p}")

    body = "\n".join(new_lines).rstrip("\n") + "\n"
    p.write_text(body, encoding="utf-8")
    return changes


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def _write_applied_bundle(target: Path, bundle: dict[str, Any]) -> SectionResult:
    """Persist the just-applied bundle as the consumer's 'last applied' state.

    Writes two sibling files under ``<target>/.ai-playbook/``:

    - ``applied-config.json`` — canonical source of truth. ``apply_config`` reads
      it on the next run; it is also the file the user re-edits or commits to
      version control externally if they want a diff trail.
    - ``applied-config.js`` — ``window.APPLIED_CONFIG = {...};`` sidecar. The
      HTML config UI loads this via ``<script src>`` so it can render the
      currently-applied state when opened over ``file://`` (where ``fetch()``
      is blocked by most browsers). The data is identical to the JSON.

    Both files are gitignored. The JS sidecar is regenerated on every apply,
    so a manual edit to the JSON without re-running ``apply_config`` will leave
    the UI showing stale state until the next apply.
    """
    sr = SectionResult(name="applied-bundle", ok=True)
    try:
        state_dir = target / STATE_DIR_NAME
        state_dir.mkdir(parents=True, exist_ok=True)
        json_path = state_dir / APPLIED_BUNDLE_FILENAME
        js_path = state_dir / APPLIED_BUNDLE_JS_FILENAME
        body = json.dumps(bundle, indent=2, ensure_ascii=False, sort_keys=False)
        json_path.write_text(body + "\n", encoding="utf-8")
        js_body = (
            "/* Auto-generated by scripts/apply_config.py. DO NOT EDIT MANUALLY. */\n"
            "/* Source of truth: applied-config.json (sibling). */\n"
            f"window.APPLIED_CONFIG = {body};\n"
        )
        js_path.write_text(js_body, encoding="utf-8")
        sr.changes.append(f"wrote {json_path}")
        sr.changes.append(f"wrote {js_path}")
    except OSError as e:
        sr.ok = False
        sr.detail = f"failed to persist applied bundle: {e}"
    return sr


def apply(bundle_path: Path, *, target: Path | None = None, dry_run: bool = False) -> ApplyReport:
    bundle_path = bundle_path.expanduser().resolve()
    if not bundle_path.is_file():
        raise FileNotFoundError(f"bundle not found: {bundle_path}")
    raw = bundle_path.read_text(encoding="utf-8")
    try:
        bundle = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"bundle is not valid JSON: {e}") from e

    schema = _load_bundle_schema()
    try:
        jsonschema.validate(bundle, schema)
    except jsonschema.ValidationError as e:
        raise ValueError(f"bundle fails schema validation: {e.message}") from e

    if target is None:
        target = rules_toggle.find_project_root()
        if target is None:
            raise FileNotFoundError(
                "target project root not found (no AGENTS.md on parent chain). "
                "Pass --target PATH."
            )
    target = target.expanduser().resolve()

    report = ApplyReport(target=target, bundle_path=bundle_path)

    rules_inv = _load_inventory("rules-inventory.json")
    global_flags_inv = _load_inventory("global-flags-inventory.json")

    if dry_run:
        # Section results in dry-run mode are descriptive only.
        sr = SectionResult(name="rules", ok=True)
        sr.detail = f"DRY-RUN would write {len(bundle.get('rules') or {})} rule entries"
        report.sections.append(sr)
        report.sections.append(apply_caveman(target, (bundle.get("features") or {}).get("caveman"), dry_run=True))
        sr2 = SectionResult(name="global_flags", ok=True)
        sr2.detail = f"DRY-RUN would write {len(bundle.get('global_flags') or {})} global flag entries"
        report.sections.append(sr2)
        sr3 = SectionResult(name="applied-bundle", ok=True)
        sr3.detail = "DRY-RUN would persist applied-config.json + applied-config.js"
        report.sections.append(sr3)
        return report

    # Section 1: rules (also produces env entries for advanced sub-toggles)
    rules_sr, rules_env_entries = apply_rules(target, bundle, rules_inv)
    report.sections.append(rules_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:rules",
        "ok": rules_sr.ok,
        "detail": rules_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 2: features.caveman
    cv_sr = apply_caveman(target, (bundle.get("features") or {}).get("caveman"))
    report.sections.append(cv_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:caveman",
        "ok": cv_sr.ok,
        "detail": cv_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 3: global_flags (merges rules-derived env entries)
    gf_sr = apply_global_flags(target, bundle, rules_env_entries, global_flags_inv)
    report.sections.append(gf_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:global_flags",
        "ok": gf_sr.ok,
        "detail": gf_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 4: persist the applied bundle as the new source of truth + UI
    # sidecar. Runs LAST so the JS file always reflects the post-apply state
    # (i.e. what the UI should render on next open). Best-effort.
    ab_sr = _write_applied_bundle(target, bundle)
    report.sections.append(ab_sr)

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="apply_config",
        description="Apply an ai-playbook-config/v1 bundle JSON to a consumer.",
    )
    parser.add_argument("bundle", type=Path, help="Path to the bundle JSON.")
    parser.add_argument("--target", type=Path, default=None,
                        help="Target project root (default: auto-discover by walking up for AGENTS.md).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Describe actions without performing them.")
    parser.add_argument("--json", action="store_true",
                        help="Emit a JSON report on stdout (default: Markdown).")
    args = parser.parse_args(argv)

    try:
        report = apply(args.bundle, target=args.target, dry_run=args.dry_run)
    except FileNotFoundError as e:
        print(f"❌ {e}", file=sys.stderr)
        return 2
    except ValueError as e:
        print(f"❌ {e}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(report.to_dict(), indent=2, ensure_ascii=False))
    else:
        print(report.to_markdown())

    return 0 if report.ok else 1


if __name__ == "__main__":
    sys.exit(main())
