"""Apply an ``ai-playbook-config/v1`` bundle JSON to a consumer project.

Bundle exported by ``config-ui/index.html`` (HTML UI) lands here. The
script projects each section to its on-disk representation:

    rules{}            → <target>/.ai-playbook/rules-toggle.json (direct write)
    features.caveman   → subprocess: python -m scripts.caveman on/off ...
    features.graphify  → subprocess: python -m scripts.graphify on/off ...
    features.ponytail  → subprocess: python -m scripts.ponytail on/off ...
    global_flags{}     → <target>/.ai-playbook/feature-flags.env (marker block)

Per-rule ``advanced{}`` sub-toggles (e.g. ``apply-skill-enforcement.advanced.bash_inspection``)
also project to the env file via the rules-inventory mapping. The L1 hook keeps
reading the env var as before; the bundle is just the declarative source.

Per the schema literal in ``schema-caveman-toggle-v1.json``:

> UI consumers MUST go through the CLI (python -m scripts.caveman) rather
> than touching the file directly.

So we subprocess. The caveman CLI handles backups, materialisation of the
AGENTS.md auto-managed block, and MCP wrapping — none of which we want to
re-implement.

Policy on errors: **best-effort per section**. A failure in one section is
reported in the audit log + the result, but the other sections still run.
Exit code is 0 if all sections succeeded, 1 if any failed.

CLI
---
    python -m scripts.apply_config <bundle.json> [--target PATH] [--dry-run] [--json]

Exit codes
----------
    0   all sections applied successfully (no-op sections count as success)
    1   one or more sections failed; see report
    2   environment/setup error (schema missing, jsonschema absent, ...)
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

from scripts._ensure_deps import ensure_runtime_deps  # noqa: E402

ensure_runtime_deps("jsonschema")
import jsonschema  # noqa: E402

from scripts import (  # noqa: E402
    _enforce_state,  # noqa: E402
    _managed_files,  # noqa: E402
    rules_toggle,  # noqa: E402
)

STATE_DIR_NAME = ".ai-playbook"
ENFORCE_STATE_DIR_NAME = _enforce_state.STATE_DIR_NAME
FEATURE_FLAGS_FILENAME = "feature-flags.env"
AUDIT_FILENAME = rules_toggle.AUDIT_FILENAME
APPLIED_BUNDLE_FILENAME = "applied-config.json"
APPLIED_BUNDLE_JS_FILENAME = "applied-config.js"
ENV_MARKER_BEGIN = "# >>> ai-playbook-config: generated by apply_config — DO NOT EDIT MANUALLY >>>"
ENV_MARKER_END = "# <<< ai-playbook-config <<<"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


@dataclass
class SectionResult:
    name: str
    ok: bool
    detail: str = ""
    changes: list[str] = field(default_factory=list)
    # Stable identity for the ordered section registry. Defaults to ``name``
    # when not set explicitly (see SECTION_ORDER).
    section_id: str = ""


@dataclass
class ApplyReport:
    target: Path
    bundle_path: Path
    sections: list[SectionResult] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return all(s.ok for s in self.sections)

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "target": self.target.as_posix(),
            "bundle_path": self.bundle_path.as_posix(),
            "sections": [
                {
                    "name": s.name,
                    "section_id": s.section_id or s.name,
                    "ok": s.ok,
                    "detail": s.detail,
                    "changes": s.changes,
                }
                for s in self.sections
            ],
        }

    def to_markdown(self) -> str:
        lines = ["# apply_config report", f"- target: `{self.target}`", f"- bundle: `{self.bundle_path}`", ""]
        for s in self.sections:
            sig = "✅" if s.ok else "❌"
            lines.append(f"## {sig} {s.name}")
            if s.detail:
                lines.append(s.detail)
            for c in s.changes:
                lines.append(f"- {c}")
            lines.append("")
        return "\n".join(lines)


def _load_bundle_schema() -> dict[str, Any]:
    root = rules_toggle.find_playbook_root()
    if root is None:
        raise FileNotFoundError(
            "ai-playbook root not found (need specs/ + scripts/ + schemas/ on parent chain)."
        )
    p = root / "schemas" / "schema-ai-playbook-config-v1.json"
    if not p.is_file():
        raise FileNotFoundError(f"Schema not found: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _load_inventory(name: str) -> dict[str, Any] | None:
    """Load a config-ui/<name>-inventory.json file. Returns None if missing."""
    root = rules_toggle.find_playbook_root()
    if root is None:
        return None
    p = root / "config-ui" / name
    if not p.is_file():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _load_rules_inventory_live() -> dict[str, Any] | None:
    """Rules inventory for the door — built LIVE from the rule artifacts (D18).

    The committed ``config-ui/rules-inventory.json`` exists for the file:// UI;
    the door must NOT trust it for the advanced→env projection (a stale commit
    would silently drop env vars). So build it from disk here. Fall back to the
    committed file only when the playbook root is unavailable (e.g. a detached
    consumer without the build context).
    """
    root = rules_toggle.find_playbook_root()
    if root is not None:
        try:
            return rules_toggle.build_rules_inventory(root)
        except Exception:  # noqa: BLE001 — fall back to the committed file
            pass
    return _load_inventory("rules-inventory.json")


def _audit_append(target: Path, entry: dict[str, Any]) -> None:
    p = target / STATE_DIR_NAME / AUDIT_FILENAME
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        with p.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False, sort_keys=True) + "\n")
    except OSError:
        pass


def _actor() -> str:
    return os.environ.get("USER") or os.environ.get("USERNAME") or "unknown"


def _caveman_preflight(target: Path) -> dict[str, Any] | None:
    """Snapshot caveman's enabled-state BEFORE any mutation this reconcile.

    caveman is a non-transactional subprocess: it mutates AGENTS.md + its state
    file at section 2 (it must run before MCP render so the ``mcp_shrink``
    post-hook sees the rendered ``.mcp.json``). If a LATER section (managed
    files) fails and rolls its batch back, caveman's changes are NOT covered by
    that session backup. This snapshot lets the report tell the operator exactly
    what state to restore caveman to. Best-effort: ``None`` when caveman is not
    installed or its state is unreadable.
    """
    try:
        from scripts.caveman import toggle as _caveman_toggle

        return _caveman_toggle.read_state(target)
    except Exception:  # noqa: BLE001 — pre-flight is advisory only
        return None


def _graphify_preflight(target: Path) -> dict[str, Any] | None:
    """Snapshot graphify's enabled-state BEFORE any mutation this reconcile.

    Like caveman, graphify is a non-transactional subprocess that mutates
    AGENTS.md (+ .gitignore) before the managed-files batch. If that batch rolls
    back, graphify's changes are not covered — this snapshot lets the report tell
    the operator what state to restore. Best-effort: ``None`` when graphify is
    not installed or its state is unreadable.
    """
    try:
        from scripts.graphify import toggle as _graphify_toggle

        return _graphify_toggle.read_state(target)
    except Exception:  # noqa: BLE001 — pre-flight is advisory only
        return None


def _ponytail_preflight(target: Path) -> dict[str, Any] | None:
    """Snapshot ponytail's enabled-state BEFORE any mutation this reconcile.

    Like caveman/graphify, ponytail is a non-transactional subprocess that mutates
    AGENTS.md before the managed-files batch. If that batch rolls back, ponytail's
    changes are not covered — this snapshot lets the report tell the operator what
    state to restore. Best-effort: ``None`` when ponytail is not installed or its
    state is unreadable.
    """
    try:
        from scripts.ponytail import toggle as _ponytail_toggle

        return _ponytail_toggle.read_state(target)
    except Exception:  # noqa: BLE001 — pre-flight is advisory only
        return None


# ---------------------------------------------------------------------------
# Section 1: rules
# ---------------------------------------------------------------------------


def apply_rules(
    target: Path, bundle: dict[str, Any], rules_inventory: dict[str, Any] | None
) -> tuple[SectionResult, dict[str, str]]:
    """Write rules-toggle.json + return env var entries derived from advanced{}.

    Returns (SectionResult, env_entries) where env_entries is a dict of
    {ENV_VAR: VALUE} to be merged into feature-flags.env by the global-flags
    section. Empty dict if no advanced sub-toggles diverged from defaults.
    """
    sr = SectionResult(name="rules", ok=True)
    rules = bundle.get("rules") or {}
    env_entries: dict[str, str] = {}

    if not rules:
        sr.detail = "no rules in bundle — no-op"
        return sr, env_entries

    # Build the state file dict.
    state = rules_toggle.default_state()
    state["rules"] = {}
    state["applied_at"] = datetime.now(UTC).isoformat()
    state["applied_by"] = _actor()

    # Orphan prune (D-plan Fase B): a bundle slug absent from the live inventory
    # is a rule that no longer exists on disk — drop it so deleting a rule never
    # leaves dangling consumer toggle state. Guard: only prune when we actually
    # have an inventory; `None` (transient build error / detached consumer) keeps
    # every slug so a missing inventory never silently wipes valid toggles.
    known: set[str] | None = None
    if rules_inventory is not None:
        known = {r.get("slug") for r in rules_inventory.get("rules", [])}

    for slug, entry in rules.items():
        if not isinstance(entry, dict):
            sr.ok = False
            sr.detail = f"rule {slug!r} is not a dict"
            return sr, env_entries
        if known is not None and slug not in known:
            sr.changes.append(f"pruned unknown rule: {slug}")
            continue
        state["rules"][slug] = dict(entry)
        sr.changes.append(f"{slug}: {('OFF' if entry.get('enabled') is False else 'partial')}")

    try:
        rules_toggle.write_state(target, state)
    except Exception as e:  # noqa: BLE001 — surface to report
        sr.ok = False
        sr.detail = f"failed to write rules-toggle.json: {e}"
        return sr, env_entries
    sr.changes.append(f"wrote {rules_toggle.state_path(target)}")

    # Derive env entries from advanced{} via inventory mapping.
    if rules_inventory is not None:
        inv_by_slug = {r["slug"]: r for r in rules_inventory.get("rules", [])}
        for slug, entry in rules.items():
            advanced = entry.get("advanced") or {}
            inv_rule = inv_by_slug.get(slug)
            if not inv_rule:
                continue
            for adv in inv_rule.get("advanced", []) or []:
                key = adv.get("key")
                if key is None or key not in advanced:
                    continue
                value = advanced[key]
                env_var = adv.get("env_var")
                if not env_var:
                    continue
                v_on = adv.get("value_on", "1")
                v_off = adv.get("value_off", "0")
                env_entries[env_var] = v_on if value else v_off

    return sr, env_entries


# ---------------------------------------------------------------------------
# Section 2: features.caveman (subprocess delegation)
# ---------------------------------------------------------------------------


def apply_caveman(target: Path, caveman_intent: dict[str, Any] | None, *, dry_run: bool = False) -> SectionResult:
    sr = SectionResult(name="features.caveman", ok=True)
    if not caveman_intent:
        sr.detail = "no caveman intent in bundle — no-op"
        return sr

    enabled = bool(caveman_intent.get("enabled"))
    mode = caveman_intent.get("mode", "ultra")
    components_dict = caveman_intent.get("components") or {}
    requested = [k for k, v in components_dict.items() if v]

    if dry_run:
        if enabled:
            sr.changes.append(
                f"DRY-RUN would invoke: python -m scripts.caveman on --mode {mode} "
                f"--components {','.join(requested) or 'response_style'}"
            )
        else:
            sr.changes.append("DRY-RUN would invoke: python -m scripts.caveman off")
        return sr

    if enabled:
        cmd = [sys.executable, "-m", "scripts.caveman", "on", "--mode", mode]
        if requested:
            cmd.extend(["--components", ",".join(requested)])
    else:
        cmd = [sys.executable, "-m", "scripts.caveman", "off"]

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(target),
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except OSError as e:
        sr.ok = False
        sr.detail = f"subprocess launch failed: {e}"
        return sr

    if proc.returncode != 0:
        sr.ok = False
        sr.detail = (
            f"caveman CLI exit {proc.returncode}\n"
            f"  stdout: {proc.stdout.strip()[:500]}\n"
            f"  stderr: {proc.stderr.strip()[:500]}"
        )
        return sr
    sr.changes.append(f"invoked: {' '.join(cmd)}")
    if proc.stdout.strip():
        sr.changes.append(f"caveman output: {proc.stdout.strip()[:300]}")
    return sr


# ---------------------------------------------------------------------------
# Section 2b: features.graphify (subprocess delegation)
# ---------------------------------------------------------------------------


def apply_graphify(target: Path, graphify_intent: dict[str, Any] | None, *, dry_run: bool = False) -> SectionResult:
    sr = SectionResult(name="features.graphify", ok=True)
    if not graphify_intent:
        sr.detail = "no graphify intent in bundle — no-op"
        return sr

    enabled = bool(graphify_intent.get("enabled"))
    components_dict = graphify_intent.get("components") or {}
    requested = [k for k, v in components_dict.items() if v]
    default_components = "agent_guidance,gitignore_hygiene"

    if dry_run:
        if enabled:
            sr.changes.append(
                "DRY-RUN would invoke: python -m scripts.graphify on "
                f"--components {','.join(requested) or default_components}"
            )
        else:
            sr.changes.append("DRY-RUN would invoke: python -m scripts.graphify off")
        return sr

    if enabled:
        cmd = [sys.executable, "-m", "scripts.graphify", "on"]
        if requested:
            cmd.extend(["--components", ",".join(requested)])
    else:
        cmd = [sys.executable, "-m", "scripts.graphify", "off"]

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(target),
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except OSError as e:
        sr.ok = False
        sr.detail = f"subprocess launch failed: {e}"
        return sr

    if proc.returncode != 0:
        sr.ok = False
        sr.detail = (
            f"graphify CLI exit {proc.returncode}\n"
            f"  stdout: {proc.stdout.strip()[:500]}\n"
            f"  stderr: {proc.stderr.strip()[:500]}"
        )
        return sr
    sr.changes.append(f"invoked: {' '.join(cmd)}")
    if proc.stdout.strip():
        sr.changes.append(f"graphify output: {proc.stdout.strip()[:300]}")
    return sr


# ---------------------------------------------------------------------------
# Section 2c: features.ponytail (subprocess delegation)
# ---------------------------------------------------------------------------


def apply_ponytail(target: Path, ponytail_intent: dict[str, Any] | None, *, dry_run: bool = False) -> SectionResult:
    sr = SectionResult(name="features.ponytail", ok=True)
    if not ponytail_intent:
        sr.detail = "no ponytail intent in bundle — no-op"
        return sr

    enabled = bool(ponytail_intent.get("enabled"))
    mode = ponytail_intent.get("mode", "ultra")
    components_dict = ponytail_intent.get("components") or {}
    requested = [k for k, v in components_dict.items() if v]

    if dry_run:
        if enabled:
            sr.changes.append(
                f"DRY-RUN would invoke: python -m scripts.ponytail on --mode {mode} "
                f"--components {','.join(requested) or 'code_style'}"
            )
        else:
            sr.changes.append("DRY-RUN would invoke: python -m scripts.ponytail off")
        return sr

    if enabled:
        cmd = [sys.executable, "-m", "scripts.ponytail", "on", "--mode", mode]
        if requested:
            cmd.extend(["--components", ",".join(requested)])
    else:
        cmd = [sys.executable, "-m", "scripts.ponytail", "off"]

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(target),
            capture_output=True,
            text=True,
            check=False,
            encoding="utf-8",
            errors="replace",
        )
    except OSError as e:
        sr.ok = False
        sr.detail = f"subprocess launch failed: {e}"
        return sr

    if proc.returncode != 0:
        sr.ok = False
        sr.detail = (
            f"ponytail CLI exit {proc.returncode}\n"
            f"  stdout: {proc.stdout.strip()[:500]}\n"
            f"  stderr: {proc.stderr.strip()[:500]}"
        )
        return sr
    sr.changes.append(f"invoked: {' '.join(cmd)}")
    if proc.stdout.strip():
        sr.changes.append(f"ponytail output: {proc.stdout.strip()[:300]}")
    return sr


# ---------------------------------------------------------------------------
# Section 3: global_flags (env file with marker block)
# ---------------------------------------------------------------------------


def apply_global_flags(
    target: Path,
    bundle: dict[str, Any],
    rules_env_entries: dict[str, str],
    global_flags_inventory: dict[str, Any] | None,
) -> SectionResult:
    sr = SectionResult(name="global_flags", ok=True)

    flag_intents = bundle.get("global_flags") or {}
    # Merge: rules-derived env entries come first (advanced sub-toggles), then
    # global_flags overlay on top (global wins on collision — unlikely but
    # explicit).
    env_entries: dict[str, str] = dict(rules_env_entries)

    if global_flags_inventory is not None:
        inv_by_key = {f["key"]: f for f in global_flags_inventory.get("flags", [])}
        for key, value in flag_intents.items():
            spec = inv_by_key.get(key)
            if spec is None:
                sr.changes.append(f"⚠ unknown global flag {key!r}; skipped")
                continue
            env_var = spec.get("env_var")
            if not env_var:
                continue
            v_on = spec.get("value_on", "1")
            v_off = spec.get("value_off", "")
            env_entries[env_var] = v_on if value else v_off

    if not env_entries and not flag_intents:
        sr.detail = "no global_flags or rules-derived env entries — no-op"
        return sr

    try:
        changes = _write_env_block(target, env_entries)
    except OSError as e:
        sr.ok = False
        sr.detail = f"failed to write feature-flags.env: {e}"
        return sr
    sr.changes.extend(changes)
    return sr


def _write_env_block(target: Path, env_entries: dict[str, str]) -> list[str]:
    """Write/update the marker block in <target>/.ai-playbook/feature-flags.env.

    Idempotent: if the file already contains the marker block, the block is
    replaced in place. If not, the block is appended (creating the file if
    needed). Lines outside the markers are preserved.

    Empty env_entries clears the block (writes the markers with no content
    inside, so future appends are still recognised).
    """
    p = target / STATE_DIR_NAME / FEATURE_FLAGS_FILENAME
    p.parent.mkdir(parents=True, exist_ok=True)

    text = p.read_text(encoding="utf-8") if p.is_file() else ""

    lines = text.split("\n")
    begin_idx = end_idx = None
    for i, line in enumerate(lines):
        if line == ENV_MARKER_BEGIN and begin_idx is None:
            begin_idx = i
        elif line == ENV_MARKER_END and begin_idx is not None and end_idx is None:
            end_idx = i

    new_block = [ENV_MARKER_BEGIN]
    for k in sorted(env_entries):
        v = env_entries[k]
        new_block.append(f"{k}={v}")
    new_block.append(ENV_MARKER_END)

    changes: list[str] = []
    if begin_idx is not None and end_idx is not None:
        # Replace existing block.
        new_lines = lines[:begin_idx] + new_block + lines[end_idx + 1:]
        changes.append(f"replaced env block ({end_idx - begin_idx - 1} → {len(env_entries)} entries)")
    else:
        # Append new block. Ensure single blank line separator if text exists.
        existing = [ln for ln in lines if ln.strip() != ""]
        new_lines = list(existing)
        if new_lines:
            new_lines.append("")
        new_lines.extend(new_block)
        new_lines.append("")
        changes.append(f"appended new env block ({len(env_entries)} entries) to {p}")

    body = "\n".join(new_lines).rstrip("\n") + "\n"
    p.write_text(body, encoding="utf-8")
    return changes


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def _apply_enforce_section(
    *,
    target: Path,
    bundle_section: dict[str, Any] | None,
    state_path: Path,
    schema_literal: str,
    section_label: str,
) -> SectionResult:
    """Project a `*_enforce` bundle section to its state file under
    `.ai-playbook-state/`.

    Negative-list contract: only the ``disabled`` array is persisted plus the
    schema literal + an ``applied_at`` timestamp. Empty ``disabled`` array is
    a legitimate explicit "everything enforced" intent — still written to disk
    so downstream readers see a deterministic file rather than a missing one.

    No-op when ``bundle_section`` is ``None`` (the bundle did not include the
    section at all). The existing state file is left untouched.
    """
    sr = SectionResult(name=section_label, ok=True)
    if bundle_section is None:
        sr.detail = f"no {section_label} intent in bundle — state file untouched"
        return sr

    disabled = bundle_section.get("disabled")
    if disabled is None:
        disabled = []
    if not isinstance(disabled, list):
        sr.ok = False
        sr.detail = f"{section_label}.disabled must be a list of slugs"
        return sr

    payload: dict[str, Any] = {
        "schema": schema_literal,
        "disabled": sorted({str(s) for s in disabled if isinstance(s, str)}),
        "applied_at": datetime.now(UTC).isoformat(),
    }
    actor = _actor()
    if actor:
        payload["applied_by"] = actor

    try:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        state_path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        sr.changes.append(
            f"wrote {state_path} ({len(payload['disabled'])} disabled entr"
            f"{'y' if len(payload['disabled']) == 1 else 'ies'})"
        )
    except OSError as e:
        sr.ok = False
        sr.detail = f"failed to write {state_path}: {e}"
    return sr


def apply_skills_enforce(
    target: Path, bundle: dict[str, Any], *, dry_run: bool = False
) -> SectionResult:
    """Section: skills_enforce → <target>/.ai-playbook-state/skills-enforce.json."""
    section = bundle.get("skills_enforce")
    if dry_run:
        sr = SectionResult(name="skills_enforce", ok=True)
        sr.detail = (
            f"DRY-RUN would write {len((section or {}).get('disabled') or [])} disabled skill(s) "
            "to .ai-playbook-state/skills-enforce.json"
            if section is not None else "DRY-RUN: no skills_enforce in bundle — no-op"
        )
        return sr
    return _apply_enforce_section(
        target=target,
        bundle_section=section,
        state_path=_enforce_state.skills_state_path(target),
        schema_literal=_enforce_state.SKILLS_SCHEMA,
        section_label="skills_enforce",
    )


def apply_mcps_enforce(
    target: Path, bundle: dict[str, Any], *, dry_run: bool = False
) -> SectionResult:
    """Section: mcps_enforce → <target>/.ai-playbook-state/mcps-enforce.json."""
    section = bundle.get("mcps_enforce")
    if dry_run:
        sr = SectionResult(name="mcps_enforce", ok=True)
        sr.detail = (
            f"DRY-RUN would write {len((section or {}).get('disabled') or [])} disabled MCP(s) "
            "to .ai-playbook-state/mcps-enforce.json"
            if section is not None else "DRY-RUN: no mcps_enforce in bundle — no-op"
        )
        return sr
    return _apply_enforce_section(
        target=target,
        bundle_section=section,
        state_path=_enforce_state.mcps_state_path(target),
        schema_literal=_enforce_state.MCPS_SCHEMA,
        section_label="mcps_enforce",
    )


# ---------------------------------------------------------------------------
# Section ordering + enforce consequences
# ---------------------------------------------------------------------------


# Ordered identity of the sections apply() emits. Child consequences
# (materialise / render) follow their parent enforce section. This replaces the
# hand-typed "Section N" comments (which had a duplicate "Section 5").
SECTION_ORDER = (
    "rules",
    "features.caveman",
    "features.graphify",
    "features.ponytail",
    "global_flags",
    "global_flags.telemetry_weekly_issue",
    "skills_enforce",
    "skills_enforce.materialise",
    "mcps_enforce",
    "mcps_enforce.render",
    "managed_files",
    "applied-bundle",
    "files-state-sidecar",
    "dashboard-sidecar",
)


_MCP_BUNDLE_SECTIONS: tuple[str, ...] = ("mcps_enforce", "mcp_project_servers")


def _has_mcp_intent(bundle: dict[str, Any]) -> bool:
    """True when the bundle carries an MCP-related section.

    ``apply_mcp_render`` re-renders ``.mcp.json`` + ``.gemini/settings.json`` (and
    a global gemini config) from the MCP SSOT. That render is the *consequence* of
    an MCP intent — running it for a bundle that says nothing about MCP (e.g. a
    caveman-only toggle) rewrites the consumer's entire MCP surface for an
    unrelated change. Gate it on a declared MCP section.
    """
    return any(section in bundle for section in _MCP_BUNDLE_SECTIONS)


def _skipped_mcp_render_section(*, dry_run: bool = False) -> SectionResult:
    """The ``mcps_enforce.render`` slot, reported as a no-op when MCP intent absent."""
    prefix = "DRY-RUN: " if dry_run else ""
    return SectionResult(
        name="mcps_enforce.render",
        section_id="mcps_enforce.render",
        ok=True,
        detail=(
            f"{prefix}skipped — no MCP intent in bundle "
            "(mcps_enforce / mcp_project_servers absent)"
        ),
    )


_TELEMETRY_WORKFLOW_REL = ".github/workflows/rule-event-report-weekly.yml"
_TELEMETRY_WORKFLOW_TMPL = (
    "templates/new-project/.github/workflows/rule-event-report-weekly.yml.tmpl"
)


def apply_telemetry_weekly_issue(
    target: Path, bundle: dict[str, Any], *, dry_run: bool = False
) -> SectionResult:
    """Consequence of the ``telemetry_weekly_issue`` global flag.

    When ON, **seed** the weekly telemetry-report workflow into the consumer's
    ``.github/workflows/`` (the ``telemetry-report`` label is created at install
    by ``bootstrap``). Seed-only: an existing file is never clobbered — the
    consumer owns it once seeded (delete it to re-seed an updated version, or to
    turn the feature off). When the flag is OFF/absent this is a no-op; removal of
    an already-seeded file is a documented manual step (a scheduled workflow can't
    read the gitignored bundle, so the file's presence IS the toggle).

    Best-effort: a missing playbook root or a write failure is reported but never
    flips the overall apply verdict.
    """
    sr = SectionResult(
        name="global_flags.telemetry_weekly_issue",
        section_id="global_flags.telemetry_weekly_issue",
        ok=True,
    )
    enabled = bool((bundle.get("global_flags") or {}).get("telemetry_weekly_issue"))
    prefix = "DRY-RUN: " if dry_run else ""
    if not enabled:
        sr.detail = f"{prefix}skipped — telemetry_weekly_issue flag off/absent"
        return sr

    dest = target / _TELEMETRY_WORKFLOW_REL
    if dest.is_file():
        sr.detail = f"{prefix}seed-only: {_TELEMETRY_WORKFLOW_REL} already present — kept as-is"
        return sr

    if dry_run:
        sr.detail = f"DRY-RUN: would seed {_TELEMETRY_WORKFLOW_REL}"
        return sr

    try:
        root = rules_toggle.find_playbook_root()
        if root is None:
            sr.detail = "skipped: playbook root not found — cannot seed workflow"
            return sr
        tmpl = root / _TELEMETRY_WORKFLOW_TMPL
        content = tmpl.read_text(encoding="utf-8")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        sr.detail = f"seeded {_TELEMETRY_WORKFLOW_REL} (telemetry-report label created at install)"
        sr.changes.append(f"+ {_TELEMETRY_WORKFLOW_REL}")
    except Exception as exc:  # noqa: BLE001 — never abort apply on a seed failure
        sr.detail = f"skipped: seed raised {type(exc).__name__}: {exc}"
    return sr


def apply_skills_materialise(target: Path, *, dry_run: bool = False) -> SectionResult:
    """Consequence of ``skills_enforce``: mirror the enforcement-filtered skills.

    Best-effort: a source-missing consumer (submodule not yet initialised) or a
    write failure is reported in the section detail but does NOT flip the overall
    apply verdict — matching the established bootstrap discipline of warning and
    continuing on skills errors.
    """
    sr = SectionResult(
        name="skills_enforce.materialise",
        section_id="skills_enforce.materialise",
        ok=True,
    )
    try:
        from scripts.materialise_skills import materialise_skills

        res = materialise_skills(target, dry_run=dry_run, quiet=True)
        sr.detail = res.summary or ("dry-run" if dry_run else "materialised")
        if res.user_dirs_preserved:
            sr.changes.append(
                f"preserved {len(res.user_dirs_preserved)} user-added skill dir(s)"
            )
        if res.stale_removed:
            sr.changes.append(
                f"removed {len(res.stale_removed)} stale playbook skill dir(s)"
            )
        if res.errors:
            sr.changes.append("⚠ " + "; ".join(res.errors)[:300])
    except Exception as exc:  # noqa: BLE001 — never abort apply on materialise
        sr.detail = f"skipped: materialise raised {type(exc).__name__}: {exc}"
    return sr


def apply_mcp_render(target: Path, *, dry_run: bool = False) -> SectionResult:
    """Consequence of ``mcps_enforce``: render .mcp.json + .gemini/settings.json.

    Best-effort: a render failure (e.g. playbook root not resolvable) is reported
    but does not flip the overall apply verdict.
    """
    sr = SectionResult(
        name="mcps_enforce.render",
        section_id="mcps_enforce.render",
        ok=True,
    )
    argv = ["--consumer-root", str(target)]
    if dry_run:
        argv.append("--dry-run")
    try:
        from scripts.mcp import render as _mcp_render

        rc = _mcp_render.main(argv)
        if rc == 0:
            sr.detail = (
                "would render .mcp.json + .gemini/settings.json"
                if dry_run else "rendered .mcp.json + .gemini/settings.json"
            )
        else:
            sr.detail = f"mcp render exited rc={rc}"
            sr.changes.append("⚠ MCP configs may be stale")
    except SystemExit as exc:  # render may sys.exit on a fatal gate
        sr.detail = f"skipped: mcp render exited ({getattr(exc, 'code', '?')})"
    except Exception as exc:  # noqa: BLE001 — never abort apply on render
        sr.detail = f"skipped: mcp render raised {type(exc).__name__}: {exc}"
    return sr


def _write_applied_bundle(target: Path, bundle: dict[str, Any]) -> SectionResult:
    """Persist the just-applied bundle as the consumer's 'last applied' state.

    Writes two sibling files under ``<target>/.ai-playbook/``:

    - ``applied-config.json`` — canonical source of truth. ``apply_config`` reads
      it on the next run; it is also the file the user re-edits or commits to
      version control externally if they want a diff trail.
    - ``applied-config.js`` — ``window.APPLIED_CONFIG = {...};`` sidecar. The
      HTML config UI loads this via ``<script src>`` so it can render the
      currently-applied state when opened over ``file://`` (where ``fetch()``
      is blocked by most browsers). The data is identical to the JSON.

    Both files are gitignored. The JS sidecar is regenerated on every apply,
    so a manual edit to the JSON without re-running ``apply_config`` will leave
    the UI showing stale state until the next apply.
    """
    sr = SectionResult(name="applied-bundle", ok=True)
    try:
        state_dir = target / STATE_DIR_NAME
        state_dir.mkdir(parents=True, exist_ok=True)
        json_path = state_dir / APPLIED_BUNDLE_FILENAME
        js_path = state_dir / APPLIED_BUNDLE_JS_FILENAME
        body = json.dumps(bundle, indent=2, ensure_ascii=False, sort_keys=False)
        json_path.write_text(body + "\n", encoding="utf-8")
        js_body = (
            "/* Auto-generated by scripts/apply_config.py. DO NOT EDIT MANUALLY. */\n"
            "/* Source of truth: applied-config.json (sibling). */\n"
            f"window.APPLIED_CONFIG = {body};\n"
        )
        js_path.write_text(js_body, encoding="utf-8")
        sr.changes.append(f"wrote {json_path}")
        sr.changes.append(f"wrote {js_path}")
    except OSError as e:
        sr.ok = False
        sr.detail = f"failed to persist applied bundle: {e}"
    return sr


def apply(bundle_path: Path, *, target: Path | None = None, dry_run: bool = False) -> ApplyReport:
    bundle_path = bundle_path.expanduser().resolve()
    if not bundle_path.is_file():
        raise FileNotFoundError(f"bundle not found: {bundle_path}")
    raw = bundle_path.read_text(encoding="utf-8")
    try:
        bundle = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"bundle is not valid JSON: {e}") from e

    schema = _load_bundle_schema()
    try:
        jsonschema.validate(bundle, schema)
    except jsonschema.ValidationError as e:
        raise ValueError(f"bundle fails schema validation: {e.message}") from e

    if target is None:
        target = rules_toggle.find_project_root()
        if target is None:
            raise FileNotFoundError(
                "target project root not found (no AGENTS.md on parent chain). "
                "Pass --target PATH."
            )
    target = target.expanduser().resolve()

    report = ApplyReport(target=target, bundle_path=bundle_path)

    # Pre-flight: caveman's enabled-state before any mutation, so a rolled-back
    # managed-files transaction can surface a precise manual reconcile step
    # (caveman is a subprocess and is not covered by the session rollback).
    caveman_preflight = _caveman_preflight(target)
    graphify_preflight = _graphify_preflight(target)
    ponytail_preflight = _ponytail_preflight(target)

    rules_inv = _load_rules_inventory_live()
    global_flags_inv = _load_inventory("global-flags-inventory.json")

    if dry_run:
        # Section results in dry-run mode are descriptive only.
        sr = SectionResult(name="rules", ok=True)
        sr.detail = f"DRY-RUN would write {len(bundle.get('rules') or {})} rule entries"
        report.sections.append(sr)
        report.sections.append(apply_caveman(target, (bundle.get("features") or {}).get("caveman"), dry_run=True))
        report.sections.append(apply_graphify(target, (bundle.get("features") or {}).get("graphify"), dry_run=True))
        report.sections.append(apply_ponytail(target, (bundle.get("features") or {}).get("ponytail"), dry_run=True))
        sr2 = SectionResult(name="global_flags", ok=True)
        sr2.detail = f"DRY-RUN would write {len(bundle.get('global_flags') or {})} global flag entries"
        report.sections.append(sr2)
        report.sections.append(apply_telemetry_weekly_issue(target, bundle, dry_run=True))
        report.sections.append(apply_skills_enforce(target, bundle, dry_run=True))
        report.sections.append(apply_skills_materialise(target, dry_run=True))
        report.sections.append(apply_mcps_enforce(target, bundle, dry_run=True))
        if _has_mcp_intent(bundle):
            report.sections.append(apply_mcp_render(target, dry_run=True))
        else:
            report.sections.append(_skipped_mcp_render_section(dry_run=True))
        # Dry-run managed files: count what would be touched.
        try:
            playbook_root_for_mf = rules_toggle.find_playbook_root()
            mf_dry = _managed_files.apply_managed_files(
                consumer_root=target,
                playbook_root=playbook_root_for_mf or Path("."),
                bundle=bundle,
                dry_run=True,
            )
            mf_sr_dry = SectionResult(
                name="managed_files", ok=mf_dry.ok, detail=mf_dry.detail,
            )
            mf_sr_dry.changes.extend(mf_dry.changes)
            report.sections.append(mf_sr_dry)
        except Exception as exc:  # noqa: BLE001
            report.sections.append(SectionResult(
                name="managed_files", ok=False,
                detail=f"dry-run failed: {exc}",
            ))
        sr3 = SectionResult(name="applied-bundle", ok=True)
        sr3.detail = "DRY-RUN would persist applied-config.json + applied-config.js"
        report.sections.append(sr3)
        return report

    # Section 1: rules (also produces env entries for advanced sub-toggles)
    rules_sr, rules_env_entries = apply_rules(target, bundle, rules_inv)
    report.sections.append(rules_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:rules",
        "ok": rules_sr.ok,
        "detail": rules_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 2: features.caveman. Runs before MCP render (section 5b) so the
    # mcp_shrink post-hook sees the rendered .mcp.json (locked ordering). caveman
    # is a non-transactional subprocess — track whether it actually mutated so a
    # later rollback can surface the manual reconcile step.
    cv_sr = apply_caveman(target, (bundle.get("features") or {}).get("caveman"))
    caveman_mutated = any(c.startswith("invoked:") for c in cv_sr.changes)
    report.sections.append(cv_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:caveman",
        "ok": cv_sr.ok,
        "detail": cv_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 2b: features.graphify. Like caveman, a non-transactional subprocess
    # that mutates AGENTS.md (+ .gitignore) — track whether it actually mutated so
    # a later managed-files rollback can surface the manual reconcile step.
    gx_sr = apply_graphify(target, (bundle.get("features") or {}).get("graphify"))
    graphify_mutated = any(c.startswith("invoked:") for c in gx_sr.changes)
    report.sections.append(gx_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:graphify",
        "ok": gx_sr.ok,
        "detail": gx_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 2c: features.ponytail. Like caveman/graphify, a non-transactional
    # subprocess that mutates AGENTS.md — track whether it actually mutated so a
    # later managed-files rollback can surface the manual reconcile step.
    px_sr = apply_ponytail(target, (bundle.get("features") or {}).get("ponytail"))
    ponytail_mutated = any(c.startswith("invoked:") for c in px_sr.changes)
    report.sections.append(px_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:ponytail",
        "ok": px_sr.ok,
        "detail": px_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 3: global_flags (merges rules-derived env entries)
    gf_sr = apply_global_flags(target, bundle, rules_env_entries, global_flags_inv)
    report.sections.append(gf_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:global_flags",
        "ok": gf_sr.ok,
        "detail": gf_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 3b: telemetry_weekly_issue — consequence of the global flag. Seeds
    # the weekly telemetry-report workflow when ON (label created at install).
    tw_sr = apply_telemetry_weekly_issue(target, bundle)
    report.sections.append(tw_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:telemetry_weekly_issue",
        "ok": tw_sr.ok,
        "detail": tw_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 4: skills_enforce → .ai-playbook-state/skills-enforce.json
    se_sr = apply_skills_enforce(target, bundle)
    report.sections.append(se_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:skills_enforce",
        "ok": se_sr.ok,
        "detail": se_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 4b: skills materialisation — the consequence of skills_enforce.
    # The enforce state file (written above) is the INPUT to the mirror.
    sm_sr = apply_skills_materialise(target)
    report.sections.append(sm_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:skills_materialise",
        "ok": sm_sr.ok,
        "detail": sm_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 5: mcps_enforce → .ai-playbook-state/mcps-enforce.json
    me_sr = apply_mcps_enforce(target, bundle)
    report.sections.append(me_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:mcps_enforce",
        "ok": me_sr.ok,
        "detail": me_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 5b: MCP render — the consequence of mcps_enforce. Reads the
    # disabled-MCP state file (written above) and renders the per-model configs.
    # Gated on a declared MCP intent so an unrelated bundle (e.g. a caveman-only
    # toggle) never rewrites the consumer's MCP surface + the global gemini config.
    mr_sr = (
        apply_mcp_render(target) if _has_mcp_intent(bundle)
        else _skipped_mcp_render_section()
    )
    report.sections.append(mr_sr)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:mcp_render",
        "ok": mr_sr.ok,
        "detail": mr_sr.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 6: managed files (AGENTS.md / .gitignore / .pre-commit / etc.).
    # Only renders files whose trigger section is present in the bundle so
    # legacy bundles stay no-op for this section. Updates bundle.file_states
    # in-memory; the applied-bundle persistence below picks up the new manifest.
    mf_sr_section = SectionResult(name="managed_files", ok=True)
    try:
        playbook_root_for_mf = rules_toggle.find_playbook_root()
        if playbook_root_for_mf is None:
            mf_sr_section.detail = "playbook root not found — managed_files skipped"
        else:
            session_id = f"apply-{datetime.now(UTC).strftime('%Y-%m-%dT%H-%M-%SZ')}"
            mf_result = _managed_files.apply_managed_files(
                consumer_root=target,
                playbook_root=playbook_root_for_mf,
                bundle=bundle,
                session_id=session_id,
            )
            mf_sr_section.ok = mf_result.ok
            mf_sr_section.detail = mf_result.detail
            mf_sr_section.changes.extend(mf_result.changes)
            # caveman ran (and possibly mutated AGENTS.md) before this batch; if
            # the batch rolled back, caveman's non-transactional changes are now
            # ahead of the reverted files — surface the manual reconcile step.
            if caveman_mutated and any("rolled back" in c for c in mf_result.changes):
                pre_enabled = bool((caveman_preflight or {}).get("enabled"))
                mf_sr_section.changes.append(
                    "⚠ caveman mutated AGENTS.md/state earlier this reconcile but the "
                    "managed-files batch rolled back; caveman is not transactional. "
                    f"Restore its pre-apply state with `python -m scripts.caveman "
                    f"{'on' if pre_enabled else 'off'}`, then re-run reconcile "
                    "(or `python -m scripts.caveman rollback --yes`)."
                )
            if graphify_mutated and any("rolled back" in c for c in mf_result.changes):
                gx_pre_enabled = bool((graphify_preflight or {}).get("enabled"))
                mf_sr_section.changes.append(
                    "⚠ graphify mutated AGENTS.md/.gitignore earlier this reconcile but the "
                    "managed-files batch rolled back; graphify is not transactional. "
                    f"Restore its pre-apply state with `python -m scripts.graphify "
                    f"{'on' if gx_pre_enabled else 'off'}`, then re-run reconcile."
                )
            if ponytail_mutated and any("rolled back" in c for c in mf_result.changes):
                px_pre_enabled = bool((ponytail_preflight or {}).get("enabled"))
                mf_sr_section.changes.append(
                    "⚠ ponytail mutated AGENTS.md earlier this reconcile but the "
                    "managed-files batch rolled back; ponytail is not transactional. "
                    f"Restore its pre-apply state with `python -m scripts.ponytail "
                    f"{'on' if px_pre_enabled else 'off'}`, then re-run reconcile."
                )
            if mf_result.file_states:
                existing_states = bundle.setdefault("file_states", {})
                for rel_path, state in mf_result.file_states.items():
                    existing_states[rel_path] = state
            if mf_result.restart_session_needed:
                mf_sr_section.changes.append(
                    "⟳ Files read by LLM sessions were modified. "
                    "Restart Claude Code / Gemini CLI for the changes to take effect."
                )
    except Exception as exc:  # noqa: BLE001
        mf_sr_section.ok = False
        mf_sr_section.detail = f"managed_files raised: {exc}"
    report.sections.append(mf_sr_section)
    _audit_append(target, {
        "ts": datetime.now(UTC).isoformat(),
        "actor": _actor(),
        "action": "apply-config:managed_files",
        "ok": mf_sr_section.ok,
        "detail": mf_sr_section.detail,
        "bundle": bundle_path.as_posix(),
    })

    # Section 7: persist the applied bundle as the new source of truth + UI
    # sidecar. Gated on the managed-files transaction: if managed_files failed
    # (and rolled its batch back), applied-config.json MUST NOT advance, so it
    # keeps matching the on-disk state.
    if mf_sr_section.ok:
        ab_sr = _write_applied_bundle(target, bundle)
    else:
        ab_sr = SectionResult(
            name="applied-bundle",
            section_id="applied-bundle",
            ok=False,
            detail="skipped: managed_files transaction failed — applied-config not advanced",
        )
    report.sections.append(ab_sr)

    # Section 8: regenerate files-state.js sidecar so the Files tab in the
    # config UI reflects the post-apply marker/SHA state. Best-effort —
    # failure here does NOT mark the overall apply as failed.
    fs_sr = SectionResult(name="files-state-sidecar", ok=True)
    try:
        from scripts import build_files_state as _bfs
        rc = _bfs.main(["--target", str(target), "--quiet"])
        if rc == 0:
            fs_sr.detail = "regenerated files-state.js"
        else:
            fs_sr.detail = f"build_files_state exited rc={rc}"
    except Exception as exc:  # noqa: BLE001
        fs_sr.detail = f"skipped: build_files_state raised ({exc})"
    report.sections.append(fs_sr)

    # Section 9: regenerate the telemetry-dashboard sidecar (best-effort).
    # Failure here must never break apply_config — log only.
    ds_sr = _rebuild_dashboard_sidecar(target)
    report.sections.append(ds_sr)

    return report


def _rebuild_dashboard_sidecar(target: Path) -> SectionResult:
    """Post-hook: invoke the telemetry-dashboard aggregator.

    Wrapped in try/except so any failure is captured as a non-fatal
    SectionResult — apply_config SHALL exit zero even when the aggregator
    fails (per openspec/changes/telemetry-dashboard/specs/
    telemetry-dashboard-aggregator/spec.md ``apply_config post-hook
    integration`` requirement).
    """
    sr = SectionResult(name="dashboard-sidecar", ok=True)
    try:
        # Imported lazily so apply_config keeps working on consumers that
        # have not yet bumped past the playbook version that ships this hook.
        from scripts.telemetry import build_dashboard_data
    except Exception as exc:  # noqa: BLE001 — best-effort.
        sr.ok = True  # not a failure of apply_config itself
        sr.detail = f"skipped: build_dashboard_data import failed ({exc})"
        return sr

    try:
        rc = build_dashboard_data.main([
            "--consumer-root", str(target),
            "--quiet",
        ])
    except SystemExit as exit_signal:
        rc = int(getattr(exit_signal, "code", 0) or 0)
    except Exception as exc:  # noqa: BLE001 — best-effort.
        sr.ok = True
        sr.detail = f"skipped: aggregator raised ({exc})"
        return sr

    if rc == 0:
        sr.detail = "regenerated dashboard-data.js"
    else:
        sr.detail = f"aggregator exited rc={rc} (sidecar may be stale)"
    return sr


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="apply_config",
        description="Apply an ai-playbook-config/v1 bundle JSON to a consumer.",
    )
    parser.add_argument("bundle", type=Path, help="Path to the bundle JSON.")
    parser.add_argument("--target", type=Path, default=None,
                        help="Target project root (default: auto-discover by walking up for AGENTS.md).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Describe actions without performing them.")
    parser.add_argument("--json", action="store_true",
                        help="Emit a JSON report on stdout (default: Markdown).")
    args = parser.parse_args(argv)

    try:
        report = apply(args.bundle, target=args.target, dry_run=args.dry_run)
    except FileNotFoundError as e:
        print(f"❌ {e}", file=sys.stderr)
        return 2
    except ValueError as e:
        print(f"❌ {e}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(report.to_dict(), indent=2, ensure_ascii=False))
    else:
        print(report.to_markdown())

    return 0 if report.ok else 1


if __name__ == "__main__":
    # The door is the single reconcile operation; instrument it at the entry
    # boundary so a standalone `python -m scripts.apply_config` emits the same
    # OTel span + rule-event/v2 row as any other CLI. When apply() runs
    # in-process (e.g. from bootstrap's reconcile), it nests under the caller's
    # span instead. Slug "apply_config" keeps metric continuity for the door.
    from scripts.rules._telemetry import script_emit
    sys.exit(script_emit("apply_config", main))
