"""Generate window-global ``.js`` sidecars for the config UI's committed JSON
inventories so the UI works under ``file://`` (where ``fetch()`` is blocked by
most browsers' CORS policy but ``<script src>`` is permitted).

For each committed ``config-ui/<name>.json`` listed in ``SIDECARS`` this writes a
sibling ``config-ui/<name>.js`` of the form::

    /* Auto-generated by scripts/build_ui_sidecars.py. DO NOT EDIT MANUALLY. */
    /* Source of truth: <name>.json (sibling). */
    window.<GLOBAL> = <verbatim JSON value>;

``index.html`` loads each via ``<script src>``; ``app.js`` prefers the injected
window global and falls back to ``fetch()`` when served over http(s). The
``.json`` files stay the source of truth — some are generated (``rules_toggle``,
``build_enforce_inventories``), some are hand-maintained — and the ``.js`` are
pure derived wrappers, regenerated from whatever the ``.json`` holds. This keeps
the UI a true double-click HTML while preserving the JSON for http/programmatic
use, mirroring the existing applied-config/files-state/dashboard sidecars.

CLI::

    python -m scripts.build_ui_sidecars            # write/refresh the sidecars
    python -m scripts.build_ui_sidecars --check     # CI/pre-commit gate, never writes

Exit codes::

    0 — sidecars written (or, with --check, all fresh).
    2 — (--check) a sidecar is missing or stale; (always) a source JSON is
        absent or unreadable.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

REPO_ROOT = Path(__file__).resolve().parent.parent
UI_DIR = REPO_ROOT / "config-ui"

# Ordered map: committed JSON filename -> the window global its sidecar sets.
# The global names mirror what app.js reads (window.RULES_INVENTORY, …) and the
# ``*_MISSING`` flags index.html sets on each <script>'s onerror.
SIDECARS: dict[str, str] = {
    "rules-inventory.json": "RULES_INVENTORY",
    "features-inventory.json": "FEATURES_INVENTORY",
    "global-flags-inventory.json": "GLOBAL_FLAGS_INVENTORY",
    "skills-inventory.json": "SKILLS_INVENTORY",
    "mcps-inventory.json": "MCPS_INVENTORY",
    "defaults.json": "DEFAULTS",
}

_HEADER = (
    "/* Auto-generated by scripts/build_ui_sidecars.py. DO NOT EDIT MANUALLY. */\n"
    "/* Source of truth: {src} (sibling). Loaded via <script src> so the config\n"
    "   UI can read this inventory under file:// where fetch() is blocked. */\n"
)


def _sidecar_name(json_name: str) -> str:
    """``rules-inventory.json`` -> ``rules-inventory.js``."""
    return json_name[:-5] + ".js" if json_name.endswith(".json") else json_name + ".js"


def _render_sidecar(json_name: str, global_name: str) -> str:
    """Read the committed JSON and return the exact ``.js`` sidecar text.

    The JSON value is embedded verbatim (trailing whitespace stripped) so the
    sidecar is a faithful mirror — re-serialising could drift from whatever
    formatting the source generator chose, churning ``--check`` needlessly.
    """
    raw = (UI_DIR / json_name).read_text(encoding="utf-8").rstrip()
    # A broken source JSON must not ship as a syntactically-valid-but-wrong .js.
    json.loads(raw)
    return f"{_HEADER.format(src=json_name)}window.{global_name} = {raw};\n"


def _emit_error(why: str, where: str, fix: str) -> None:
    print(f"❌ {why}\n   WHERE: {where}\n   FIX:   {fix}", file=sys.stderr)


def cmd_build(check: bool) -> int:
    if not UI_DIR.is_dir():
        _emit_error(
            why="config-ui/ directory not found",
            where=UI_DIR.as_posix(),
            fix="run from inside the ai-playbook checkout.",
        )
        return 2

    problems: list[str] = []
    written: list[str] = []
    for json_name, global_name in SIDECARS.items():
        if not (UI_DIR / json_name).is_file():
            problems.append(f"  source JSON missing: config-ui/{json_name}")
            continue
        try:
            body = _render_sidecar(json_name, global_name)
        except (OSError, json.JSONDecodeError) as e:
            problems.append(f"  config-ui/{json_name} unreadable/invalid JSON: {e}")
            continue
        out = UI_DIR / _sidecar_name(json_name)
        if check:
            if not out.is_file():
                problems.append(f"  sidecar missing: config-ui/{out.name} (run build)")
            elif out.read_text(encoding="utf-8") != body:
                problems.append(f"  sidecar stale: config-ui/{out.name} (re-run build)")
        else:
            # newline="\n" so the committed sidecars are byte-identical across
            # platforms (Windows text-mode would otherwise emit CRLF, churning
            # git normalization and the --check gate).
            out.write_text(body, encoding="utf-8", newline="\n")
            written.append(out.name)

    if problems:
        _emit_error(
            why=(
                "config-ui .js sidecars are missing or stale"
                if check
                else "could not build all config-ui sidecars"
            ),
            where=UI_DIR.as_posix(),
            fix="run `python -m scripts.build_ui_sidecars` and commit the .js files.",
        )
        for line in problems:
            print(line, file=sys.stderr)
        return 2

    if check:
        print(f"✅ {len(SIDECARS)} config-ui sidecars fresh")
    else:
        print(f"✅ wrote {len(written)} config-ui sidecars: {', '.join(written)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    p.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed .js match the .json; never write. Exit 2 on drift.",
    )
    args = p.parse_args(argv)
    return cmd_build(check=args.check)


if __name__ == "__main__":
    sys.exit(main())
