"""Generate INDEX.md files for documentation folders (docs/, specs/, …).

For each directory that contains one or more `*.md` files (excluding `INDEX.md`
itself), this script writes an `INDEX.md` with:

- An H1 heading (`# <Folder name> — index`).
- An auto-generated banner.
- A table: `File | Summary`.
  - `File` is a markdown link to the file (`[name](file.md)`).
  - `Summary` prefers a curated YAML frontmatter field (`summary:` for
    concept docs, `description:` for rules / runbooks / tutorials). Falls back
    to the first non-heading body paragraph when no frontmatter summary
    exists. Truncated to ≤200 chars, or `—` when absent.
  - Rows sorted alphabetically by filename.
- An optional `## Sub-directories` section that links each child directory's
  INDEX.md.

Every directory is treated as self-contained — the script does NOT recurse its
table content into sub-indexes; it only adds pointers.

Usage
-----
    python -m scripts.gen_indexes                   # walk docs/ and specs/ from repo root
    python -m scripts.gen_indexes --root PATH       # walk a single directory tree
    python -m scripts.gen_indexes --check           # exit 1 if any INDEX.md is stale

Exit codes
----------
    0  success
    1  --check found stale / missing INDEX.md file(s)
    2  setup failure (invalid root, etc.)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Force UTF-8 stdio — Windows default cp1252 cannot encode the ✅/❌/⚠️ sigils.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass


INDEX_FILENAME = "INDEX.md"
BANNER = "> Auto-generated by scripts/gen_indexes.py. Do not edit by hand."
SUMMARY_MAX_LEN = 200
SUMMARY_FRONTMATTER_KEYS = ("summary", "description")
DEFAULT_SUBDIRS = ("docs", "specs")

# Directories we never descend into when looking for markdown files.
IGNORE_DIRS = {
    ".git", "node_modules", ".venv", "venv", "env", "__pycache__",
    ".idea", ".vscode", "dist", "build", ".next", ".turbo",
    ".cache", ".pytest_cache", ".ruff_cache", ".mypy_cache",
    "archive",  # archived / frozen content shouldn't appear in live index
}


def _split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block, body). Frontmatter is empty when absent."""
    text = text.replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return "", text
    rest = text[4:]
    end = rest.find("\n---\n")
    if end == -1:
        end = rest.find("\n---")
        if end == -1:
            return "", text
        return rest[:end], rest[end + len("\n---"):].lstrip("\n")
    return rest[:end], rest[end + len("\n---\n"):]


def _strip_frontmatter(text: str) -> str:
    """Remove a leading YAML frontmatter block (---...---) if present."""
    return _split_frontmatter(text)[1]


def _summary_from_frontmatter(fm: str) -> str:
    """Pull the first `summary:` or `description:` value from a YAML frontmatter block.

    Supports single-line scalars (`key: value`) and `|` / `>` block scalars
    (indented continuation lines until the next top-level key or end of block).
    Returns `""` when no recognised key is present.
    """
    if not fm:
        return ""
    lines = fm.splitlines()
    for i, raw in enumerate(lines):
        # Top-level keys are non-indented.
        if not raw or raw[:1] in (" ", "\t"):
            continue
        key, sep, value = raw.partition(":")
        if not sep:
            continue
        if key.strip().lower() not in SUMMARY_FRONTMATTER_KEYS:
            continue
        value = value.strip()
        # Block scalar: read indented continuation lines and fold to a single line.
        if value in ("|", ">", "|-", ">-", "|+", ">+"):
            collected: list[str] = []
            for cont in lines[i + 1:]:
                if not cont.strip():
                    if collected:
                        collected.append("")
                    continue
                if cont[:1] not in (" ", "\t"):
                    break
                collected.append(cont.strip())
            # Fold paragraph breaks (blank lines) into a single space — index cells are one line.
            return " ".join(seg for seg in collected if seg).strip()
        # Strip surrounding quotes from a single-line scalar.
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        return value.strip()
    return ""


def _summary_from_body(body: str) -> str:
    """First content paragraph line from the body — no heading, blockquote, list, or code fence."""
    in_code_fence = False
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("```"):
            in_code_fence = not in_code_fence
            continue
        if in_code_fence:
            continue
        if line.startswith("#"):
            continue
        if line.startswith(">"):
            continue
        if line.startswith(("-", "*", "+")) and (len(line) == 1 or line[1] == " "):
            continue
        if line.startswith("|"):
            continue
        if line.startswith("<!--"):
            continue
        return line
    return ""


def extract_summary(md_text: str) -> str:
    """Curated frontmatter summary when present, else first body paragraph.

    Truncated to SUMMARY_MAX_LEN chars (with trailing `…`). Returns `—` if neither
    source yields content.
    """
    fm, body = _split_frontmatter(md_text)
    value = _summary_from_frontmatter(fm) or _summary_from_body(body)
    if not value:
        return "—"
    if len(value) > SUMMARY_MAX_LEN:
        return value[: SUMMARY_MAX_LEN - 1].rstrip() + "…"
    return value


def _escape_cell(value: str) -> str:
    """Escape characters that would break a markdown table cell."""
    # Replace pipe + newlines so they don't split the row.
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _title_for(directory: Path) -> str:
    """Humanized title for the INDEX H1."""
    name = directory.name or str(directory)
    return name


def collect_md_files(directory: Path) -> list[Path]:
    """Return sorted `*.md` files directly inside `directory`, excluding INDEX.md."""
    out: list[Path] = []
    try:
        for entry in directory.iterdir():
            if not entry.is_file():
                continue
            if entry.suffix.lower() != ".md":
                continue
            if entry.name == INDEX_FILENAME:
                continue
            out.append(entry)
    except (PermissionError, OSError):
        return []
    out.sort(key=lambda p: p.name.lower())
    return out


def collect_subdirs(directory: Path) -> list[Path]:
    """Return sorted child directories that contain at least one `*.md` (recursively)."""
    out: list[Path] = []
    try:
        for entry in directory.iterdir():
            if not entry.is_dir():
                continue
            if entry.name in IGNORE_DIRS or entry.name.startswith("."):
                continue
            if _has_markdown(entry):
                out.append(entry)
    except (PermissionError, OSError):
        return []
    out.sort(key=lambda p: p.name.lower())
    return out


def _has_markdown(directory: Path) -> bool:
    try:
        for entry in directory.rglob("*.md"):
            if entry.is_file():
                return True
    except (PermissionError, OSError):
        return False
    return False


def render_index(directory: Path) -> str:
    """Build the INDEX.md text for a directory."""
    md_files = collect_md_files(directory)
    subdirs = collect_subdirs(directory)

    lines: list[str] = []
    lines.append(f"# {_title_for(directory)} — index")
    lines.append("")
    lines.append(BANNER)
    lines.append("")

    if md_files:
        lines.append("| File | Summary |")
        lines.append("| --- | --- |")
        for path in md_files:
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                text = ""
            summary = _escape_cell(extract_summary(text))
            link = f"[{path.name}]({path.name})"
            lines.append(f"| {link} | {summary} |")
        lines.append("")
    else:
        lines.append("_No markdown files in this directory._")
        lines.append("")

    if subdirs:
        lines.append("## Sub-directories")
        lines.append("")
        for sub in subdirs:
            rel = f"{sub.name}/{INDEX_FILENAME}"
            lines.append(f"- [{sub.name}/]({rel})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _iter_index_dirs(root: Path) -> list[Path]:
    """Yield every directory under `root` that should own an INDEX.md."""
    dirs: list[Path] = []
    if not root.is_dir():
        return dirs
    # Include root itself if it has markdown
    if collect_md_files(root) or collect_subdirs(root):
        dirs.append(root)
    for entry in root.rglob("*"):
        if not entry.is_dir():
            continue
        if entry.name in IGNORE_DIRS or entry.name.startswith("."):
            continue
        # Skip directories inside an ignored ancestor
        if any(part in IGNORE_DIRS or part.startswith(".") for part in entry.relative_to(root).parts):
            continue
        if collect_md_files(entry):
            dirs.append(entry)
    # Deduplicate while preserving order
    seen: set[Path] = set()
    unique: list[Path] = []
    for d in dirs:
        key = d.resolve()
        if key in seen:
            continue
        seen.add(key)
        unique.append(d)
    return unique


def _has_curated_homepage(directory: Path) -> bool:
    """Return True if the directory already has a curated `index.md` homepage.

    When a curated homepage exists (e.g., the MkDocs docs/ root), we skip
    auto-generating INDEX.md because on case-insensitive filesystems (Windows,
    macOS default) the two names collide, and even on case-sensitive ones a
    curated homepage semantically replaces the auto-index.
    """
    try:
        for entry in directory.iterdir():
            if entry.is_file() and entry.name.lower() == "index.md" and entry.name != INDEX_FILENAME:
                return True
    except (PermissionError, OSError):
        return False
    return False


def write_index(directory: Path, *, check: bool) -> tuple[bool, bool]:
    """Render INDEX.md for `directory`.

    Returns (changed, missing):
        changed — existing content differs from desired (or would be written fresh).
        missing — INDEX.md does not exist.

    If the directory already carries a curated `index.md` homepage, the
    auto-generated INDEX.md is skipped — both in write and check modes — so we
    never collide with MkDocs's homepage convention.
    """
    if _has_curated_homepage(directory):
        return (False, False)

    target = directory / INDEX_FILENAME
    desired = render_index(directory)

    existing: str | None
    try:
        existing = target.read_text(encoding="utf-8") if target.is_file() else None
    except OSError:
        existing = None

    missing = existing is None
    changed = existing != desired

    if check:
        return (changed, missing)

    if changed:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(desired, encoding="utf-8")
    return (changed, missing)


def resolve_roots(cli_root: Path | None) -> list[Path]:
    """Determine which trees to walk."""
    if cli_root is not None:
        return [cli_root.expanduser().resolve()]
    # Default: walk `docs/` and `specs/` relative to the repo root (this file's grandparent).
    repo_root = Path(__file__).resolve().parent.parent
    roots: list[Path] = []
    for name in DEFAULT_SUBDIRS:
        candidate = repo_root / name
        if candidate.is_dir():
            roots.append(candidate)
    return roots


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_indexes",
        description="Generate INDEX.md files for docs/ and specs/ folders.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Single directory to walk. Defaults to the repo's docs/ and specs/ trees.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any INDEX.md is missing or out of date (CI mode).",
    )
    args = parser.parse_args(argv)

    roots = resolve_roots(args.root)
    if not roots:
        print(
            "❌ No directories to index at repo root\n"
            "   FIX: pass --root PATH or ensure docs/ and specs/ exist beside scripts/.\n"
            "   OVERRIDE: none",
            file=sys.stderr,
        )
        return 2

    stale: list[Path] = []
    missing_list: list[Path] = []
    written: list[Path] = []

    for root in roots:
        if not root.is_dir():
            print(
                f"❌ --root path is not a directory at {root}\n"
                f"   FIX: pass an existing directory via --root.\n"
                f"   OVERRIDE: none",
                file=sys.stderr,
            )
            return 2
        for directory in _iter_index_dirs(root):
            changed, missing = write_index(directory, check=args.check)
            if args.check:
                if missing:
                    missing_list.append(directory / INDEX_FILENAME)
                elif changed:
                    stale.append(directory / INDEX_FILENAME)
            else:
                if changed or missing:
                    written.append(directory / INDEX_FILENAME)

    if args.check:
        if missing_list or stale:
            for path in missing_list:
                print(
                    f"❌ INDEX.md missing at {path.as_posix()}\n"
                    f"   FIX: run `python -m scripts.gen_indexes` and commit the result.\n"
                    f"   OVERRIDE: none",
                    file=sys.stderr,
                )
            for path in stale:
                print(
                    f"❌ INDEX.md out of date at {path.as_posix()}\n"
                    f"   FIX: run `python -m scripts.gen_indexes` and commit the result.\n"
                    f"   OVERRIDE: none",
                    file=sys.stderr,
                )
            return 1
        print("✅ All INDEX.md files are up to date.")
        return 0

    if written:
        print(f"✅ Wrote {len(written)} INDEX.md file(s):")
        for path in written:
            print(f"  - {path.as_posix()}")
    else:
        print("✅ No changes — INDEX.md files already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
