"""D11 — generate `.cursor/rules/<slug>.mdc` from `docs/rules/<slug>.rule.md`.

Same pattern as `materialise_skills.py`: source of truth is the markdown
rule doc; the Cursor `.mdc` mirror is gitignored and regenerated by hook.

Cursor co-constraints (validated at generation time):

- `activation: auto`  ⇒ `globs:` REQUIRED
- `activation: agent` ⇒ `description:` ≤300 chars
- `activation: manual` ⇒ no auto-load — written as plain content

CLI:

    python -m scripts.materialise_cursor_rules
    python -m scripts.materialise_cursor_rules --dry-run
    python -m scripts.materialise_cursor_rules --out .cursor/rules

Exit codes:
    0 — wrote all rules cleanly
    2 — co-constraint violation
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def _parse_doc(path: Path) -> tuple[dict[str, Any], str]:
    """Return (frontmatter dict, body string)."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    fm = yaml.safe_load(text[3:end].strip()) or {}
    body = text[end + 4 :].lstrip("\n")
    return fm, body


def _validate_constraints(fm: dict[str, Any], path: Path) -> list[str]:
    errors: list[str] = []
    activation = fm.get("activation")
    if activation == "auto" and not fm.get("globs"):
        errors.append(f"{path}: activation=auto requires globs:")
    description = fm.get("description") or ""
    if activation == "agent" and len(description) > 300:
        errors.append(f"{path}: activation=agent requires description: <=300 chars (got {len(description)})")
    return errors


def _render_mdc(fm: dict[str, Any], body: str) -> str:
    """Produce a minimal Cursor .mdc payload.

    Frontmatter is a stripped-down subset of the rule frontmatter that Cursor
    knows about: description, globs, alwaysApply. Body is the rule's prose.
    """
    cursor_fm: dict[str, Any] = {}
    if "description" in fm:
        cursor_fm["description"] = fm["description"]
    if "globs" in fm:
        cursor_fm["globs"] = fm["globs"]
    if fm.get("activation") == "always":
        cursor_fm["alwaysApply"] = True
    rendered = "---\n" + yaml.safe_dump(cursor_fm, sort_keys=False).rstrip() + "\n---\n\n"
    return rendered + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Materialise Cursor .mdc from docs/rules/ (D11).")
    parser.add_argument("--out", default=str(REPO_ROOT / ".cursor" / "rules"))
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    all_errors: list[str] = []
    wrote = 0
    for doc in sorted((REPO_ROOT / "docs" / "rules").glob("*.rule.md")):
        fm, body = _parse_doc(doc)
        if not isinstance(fm, dict):
            continue
        slug = fm.get("slug")
        if not isinstance(slug, str):
            continue
        errors = _validate_constraints(fm, doc)
        if errors:
            all_errors.extend(errors)
            continue
        target = out_dir / f"{slug}.mdc"
        rendered = _render_mdc(fm, body)
        if not args.dry_run:
            target.write_text(rendered, encoding="utf-8")
        wrote += 1

    if all_errors:
        for e in all_errors:
            print(e, file=sys.stderr)
        return 2

    if not args.quiet:
        print(f"materialise_cursor_rules: OK ({wrote} rule(s) written to {out_dir})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
