"""opsx_apply_companion.py — Branch+SHA capture + pre-flight rebase.

Per release-management.md §6.5: before the AI begins implementing a slice
(i.e. before the first task commit on `slice/<change-id>`), it MUST:

1. `git fetch origin`
2. Record `git rev-parse --short origin/<default>` as the slice's
   `Base SHA` on the project board (per §5.5). The default branch is
   auto-detected from `origin/HEAD` (`main` for new repos, `master`
   for legacy repos). Override with `--default-branch <name>` if the
   detection fails (e.g. fresh clones where origin/HEAD is unset).
3. If on the slice branch: `git rebase origin/<default>`. Conflicts →
   abort, notify human reviewer (do NOT auto-resolve).
4. Set the project board's `Branch` field to `slice/<change-id>`.

This script implements that contract as a **companion** to the openspec-CLI-
generated `openspec-apply-change` skill. The skill itself is upstream-
managed (re-generated by `npx openspec`) so we cannot embed the §6.5 logic
inside it. Instead, the worker AI invokes this companion AT THE START of
its implementation work, BEFORE the first task commit:

    python -m scripts.opsx_apply_companion \\
        --change-id shared-primitives \\
        --owner Wizarck \\
        --project-number 2 \\
        --repo Wizarck/iguanatrader

The contract in `AGENTS.md` §0 (bootstrap directive) tells the AI to read
release-management.md, which references this script as the required first
step. So the AI invokes it as part of /opsx:apply.

Behaviour
---------
- Verifies clean working tree. Fails loudly if dirty (unstaged changes,
  staged-but-uncommitted, or untracked tracked files).
- Fetches origin (no submodules — those are owned by the consumer's bump
  workflows, not slice work).
- Captures `Base SHA` = short SHA of `origin/<default-branch>` post-fetch.
- If currently on `slice/<change-id>`: rebases against `origin/<default-branch>`.
  - On conflict: aborts the rebase, prints a human-readable error, exits
    1. The human reviewer is the safety net (do NOT auto-resolve).
  - No-op if already on top of origin/<default-branch>.
- If currently on a different branch: skips the rebase step, just records
  fields. (The AI may have invoked this BEFORE creating the slice branch;
  that's allowed — fields will be re-set if the AI invokes again post-
  branch-creation.)
- Sets `Branch` + `Base SHA` fields on the project item titled
  `<change-id>`. Creates the fields if absent (calls the same helpers as
  `bootstrap_gh_project.ensure_trace_fields`).

Idempotent: re-running with same args produces same final state.

Exit codes
----------
    0 — success (fields set, rebase clean or skipped)
    1 — rebase conflict; human action required (rebase aborted)
    2 — setup error (gh unavailable, project / item not found, dirty tree)
    3 — unrecoverable GraphQL error
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# Force UTF-8 stdio.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.bootstrap_gh_project import (  # noqa: E402
    _emit,
    _gh_available,
    _gh_graphql,
    ensure_trace_fields,
    list_fields,
    list_items,
    lookup_project,
)


def _git(args: list[str], *, check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        check=check,
        capture_output=capture,
        text=True,
        encoding="utf-8",
    )


def _verify_clean_tree() -> None:
    """Raise RuntimeError if the working tree is dirty."""
    r = _git(["status", "--porcelain"])
    dirty = r.stdout.strip()
    if dirty:
        raise RuntimeError(
            "working tree is dirty. Commit or stash before running "
            "/opsx:apply companion. Output:\n" + dirty
        )


def _current_branch() -> str:
    r = _git(["rev-parse", "--abbrev-ref", "HEAD"])
    return r.stdout.strip()


def _fetch_origin() -> None:
    print("→ git fetch origin")
    _git(["fetch", "origin", "--quiet"], capture=False)


def _detect_default_branch() -> str:
    """Detect the remote's default branch (`main` or `master`).

    Reads `origin/HEAD`, e.g. `refs/remotes/origin/main` → `main`.
    Falls back to a literal probe: tries `origin/main`, then
    `origin/master`. Raises if neither resolves.
    """
    # Preferred: origin/HEAD points at the symbolic remote default.
    r = _git(
        ["symbolic-ref", "refs/remotes/origin/HEAD"],
        check=False,
        capture=True,
    )
    if r.returncode == 0:
        ref = r.stdout.strip()  # e.g. refs/remotes/origin/main
        prefix = "refs/remotes/origin/"
        if ref.startswith(prefix):
            return ref[len(prefix):]
    # Fallback: probe the two common defaults.
    for candidate in ("main", "master"):
        rr = _git(
            ["rev-parse", "--verify", "--quiet", f"origin/{candidate}"],
            check=False,
            capture=True,
        )
        if rr.returncode == 0:
            return candidate
    raise RuntimeError(
        "could not detect remote default branch. Neither origin/HEAD nor "
        "origin/main nor origin/master resolves. Pass --default-branch "
        "<name> explicitly, or run `git remote set-head origin --auto`."
    )


def _capture_base_sha(default_branch: str) -> str:
    """Short SHA of `origin/<default_branch>` HEAD (post-fetch)."""
    r = _git(["rev-parse", "--short", f"origin/{default_branch}"])
    return r.stdout.strip()


def _rebase_onto_default(slice_branch: str, default_branch: str) -> None:
    """Rebase the slice branch on top of origin/<default>. Aborts on conflict."""
    target = f"origin/{default_branch}"
    print(f"→ git rebase {target} (on {slice_branch})")
    r = _git(["rebase", target], check=False, capture=True)
    if r.returncode == 0:
        print("  rebase clean (no-op or fast-forward applied)")
        return
    # Abort the rebase to leave the workspace in a clean state.
    _git(["rebase", "--abort"], check=False, capture=True)
    raise RuntimeError(
        f"rebase of {slice_branch} onto {target} has conflicts. "
        "Aborted. Resolve manually:\n"
        f"  git rebase {target}\n"
        "  # resolve conflicts, git rebase --continue\n"
        "  # OR: git rebase --abort if you want to give up\n"
        "Per release-management.md §6.5: AI must NOT auto-resolve. "
        "Notify the human reviewer."
    )


def set_item_text_field(
    project_id: str, item_id: str, field_id: str, value: str, *, dry_run: bool
) -> None:
    """Set a TEXT field on a project item via GraphQL."""
    if dry_run:
        return
    mutation = """
    mutation($project_id: ID!, $item_id: ID!, $field_id: ID!, $value: String!) {
      updateProjectV2ItemFieldValue(input: {
        projectId: $project_id,
        itemId: $item_id,
        fieldId: $field_id,
        value: { text: $value }
      }) {
        projectV2Item { id }
      }
    }
    """
    _gh_graphql(
        mutation,
        project_id=project_id,
        item_id=item_id,
        field_id=field_id,
        value=value,
    )


def _enforce_board_state(
    *, change_id: str, owner: str, project_number: int
) -> int:
    """Per project-board-sync.md L6: assert Status=In Progress on the project item.

    Returns 0 on match, non-zero on mismatch / item-not-found / GraphQL error.
    Reuses verify_board_state's exit-code semantics.
    """
    from scripts import verify_board_state  # local import to avoid circular load

    print("→ enforce-board: verifying Status='In Progress' on the project item")
    return verify_board_state.main(
        [
            "--change-id",
            change_id,
            "--owner",
            owner,
            "--project-number",
            str(project_number),
            "--expected-status",
            "In Progress",
        ]
    )


def run(
    *,
    change_id: str,
    owner: str,
    project_number: int,
    repo: str | None,
    dry_run: bool,
    default_branch: str | None = None,
    enforce_board: bool = False,
) -> int:
    if not _gh_available():
        print("error: gh CLI not authenticated; run `gh auth login` first", file=sys.stderr)
        return 2

    _emit(
        "opsx_apply_companion.start",
        change_id=change_id,
        owner=owner,
        project_number=project_number,
        repo=repo,
        dry_run=dry_run,
        default_branch=default_branch,
    )

    # 1. Verify clean tree.
    try:
        _verify_clean_tree()
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    # 2. Fetch origin.
    if dry_run:
        print("→ would: git fetch origin (dry-run)")
    else:
        _fetch_origin()

    # 2b. Resolve default branch (auto-detect unless overridden).
    if dry_run and default_branch is None:
        resolved_default = "<auto>"
    elif default_branch is not None:
        resolved_default = default_branch
        print(f"→ default branch = {resolved_default} (override via --default-branch)")
    else:
        try:
            resolved_default = _detect_default_branch()
        except RuntimeError as e:
            print(f"error: {e}", file=sys.stderr)
            return 2
        print(f"→ default branch = {resolved_default} (auto-detected from origin/HEAD)")

    # 3. Capture base SHA.
    if dry_run:
        base_sha = "<dry-run>"
        print(f"→ would: capture base SHA from origin/{resolved_default} (dry-run)")
    else:
        base_sha = _capture_base_sha(resolved_default)
        print(f"→ Base SHA = {base_sha} (origin/{resolved_default} HEAD)")

    # 4. Rebase if on slice branch.
    expected_branch = f"slice/{change_id}"
    current = _current_branch()
    if current == expected_branch:
        if dry_run:
            print(f"→ would: git rebase origin/{resolved_default} on {current} (dry-run)")
        else:
            try:
                _rebase_onto_default(current, resolved_default)
            except RuntimeError as e:
                print(f"error: {e}", file=sys.stderr)
                return 1
    else:
        print(
            f"→ skipping rebase: current branch is {current!r}, expected "
            f"{expected_branch!r}. Either you haven't created the slice "
            "branch yet (in which case this companion will run again "
            "post-creation) or you're on a different branch."
        )

    # 5. Find project + item, ensure trace fields exist, set values.
    try:
        proj = lookup_project(owner, project_number)
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    fields = list_fields(proj.id)
    # Ensure Branch + Base SHA fields exist.
    trace_added = ensure_trace_fields(proj.id, fields, dry_run=dry_run)
    if trace_added:
        # Re-fetch fields after creation.
        fields = list_fields(proj.id) if not dry_run else fields
    branch_field = next((f for f in fields if f.name == "Branch"), None)
    sha_field = next((f for f in fields if f.name == "Base SHA"), None)
    if branch_field is None or sha_field is None:
        print(
            "error: Branch and/or Base SHA fields missing on project; "
            "run `bootstrap_gh_project.py --profile auto` first.",
            file=sys.stderr,
        )
        return 2

    items = list_items(proj.id)
    item = next((it for it in items if it.title == change_id), None)
    if item is None:
        print(
            f"error: no project item with title {change_id!r}; "
            "run `bootstrap_gh_project.py --slicing-file docs/openspec-slice.md` "
            "to create it.",
            file=sys.stderr,
        )
        return 2

    if dry_run:
        print(f"→ would: set Branch={expected_branch!r} on item {change_id!r} (dry-run)")
        print(f"→ would: set Base SHA={base_sha!r} on item {change_id!r} (dry-run)")
    else:
        set_item_text_field(
            proj.id, item.id, branch_field.id, expected_branch, dry_run=dry_run
        )
        set_item_text_field(
            proj.id, item.id, sha_field.id, base_sha, dry_run=dry_run
        )
        print(f"→ Set Branch={expected_branch} on item {change_id!r}")
        print(f"→ Set Base SHA={base_sha} on item {change_id!r}")

    # L6 — board-state enforcement (opt-in). Per project-board-sync.md §2.
    # When --enforce-board is passed, verify the project item is in the
    # expected Status=In Progress before declaring success. The check runs
    # AFTER setting the Branch/Base SHA fields (which the L2 workflow may
    # not have fired yet for) — so dry-run skips it; live runs may need a
    # short retry window if L2 is racing.
    if enforce_board and not dry_run:
        rc = _enforce_board_state(
            change_id=change_id,
            owner=owner,
            project_number=project_number,
        )
        if rc != 0:
            _emit(
                "opsx_apply_companion.board_enforce_failed",
                change_id=change_id,
                exit_code=rc,
            )
            print(
                f"error: --enforce-board check failed (exit {rc}). "
                f"Likely cause: the L2 project-status-slice-progress workflow "
                f"has not fired yet OR Status got drift-set to a non-"
                f"InProgress value. See project-board-sync.md L2/L3.",
                file=sys.stderr,
            )
            return rc

    _emit(
        "opsx_apply_companion.complete",
        change_id=change_id,
        branch=expected_branch,
        base_sha=base_sha,
        rebased=(current == expected_branch),
        dry_run=dry_run,
        enforce_board=enforce_board,
    )
    print(f"✓ /opsx:apply companion done — change_id={change_id}")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=(
            "Branch + Base SHA capture + pre-flight rebase before /opsx:apply "
            "implementation work. Per release-management.md §6.5."
        )
    )
    p.add_argument(
        "--change-id",
        required=True,
        help="OpenSpec change-id (kebab-case folder name under openspec/changes/)",
    )
    p.add_argument("--owner", required=True, help="GH user or org login")
    p.add_argument("--project-number", required=True, type=int)
    p.add_argument(
        "--repo",
        default=None,
        metavar="owner/name",
        help="Consumer repo (informational; not strictly required)",
    )
    p.add_argument(
        "--default-branch",
        default=None,
        metavar="NAME",
        help=(
            "Override the auto-detected default branch (e.g. 'main', 'master'). "
            "Default: auto-detect from origin/HEAD, falling back to a probe of "
            "origin/main then origin/master. Pass this when origin/HEAD is "
            "unset (fresh clones with no remote default) or when targeting a "
            "non-canonical branch (e.g. 'develop')."
        ),
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended steps without applying them",
    )
    p.add_argument(
        "--enforce-board",
        action="store_true",
        help=(
            "L6 enforcement: after setting Branch/Base SHA, verify the project "
            "item's Status='In Progress' (delegating to verify_board_state.py). "
            "Exits non-zero on mismatch — refuses to declare success without "
            "board sync. See specs/project-board-sync.md §2 L6."
        ),
    )
    args = p.parse_args(argv)

    try:
        return run(
            change_id=args.change_id,
            owner=args.owner,
            project_number=args.project_number,
            repo=args.repo,
            dry_run=args.dry_run,
            default_branch=args.default_branch,
            enforce_board=args.enforce_board,
        )
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        _emit("opsx_apply_companion.failed", reason=str(e))
        return 3


if __name__ == "__main__":
    sys.exit(main())
