"""opsx_apply_companion.py — Branch+SHA capture + pre-flight rebase.

Per release-management.md §6.5: before the AI begins implementing a slice
(i.e. before the first task commit on `slice/<change-id>`), it MUST:

1. `git fetch origin`
2. Record `git rev-parse --short origin/main` as the slice's `Base SHA`
   on the project board (per §5.5).
3. If on the slice branch: `git rebase origin/main`. Conflicts → abort,
   notify human reviewer (do NOT auto-resolve).
4. Set the project board's `Branch` field to `slice/<change-id>`.

This script implements that contract as a **companion** to the openspec-CLI-
generated `openspec-apply-change` skill. The skill itself is upstream-
managed (re-generated by `npx openspec`) so we cannot embed the §6.5 logic
inside it. Instead, the worker AI invokes this companion AT THE START of
its implementation work, BEFORE the first task commit:

    python -m scripts.opsx_apply_companion \\
        --change-id shared-primitives \\
        --owner Wizarck \\
        --project-number 2 \\
        --repo Wizarck/consumer-e

The contract in `AGENTS.md` §0 (bootstrap directive) tells the AI to read
release-management.md, which references this script as the required first
step. So the AI invokes it as part of /opsx:apply.

Behaviour
---------
- Verifies clean working tree. Fails loudly if dirty (unstaged changes,
  staged-but-uncommitted, or untracked tracked files).
- Fetches origin (no submodules — those are owned by the consumer's bump
  workflows, not slice work).
- Captures `Base SHA` = short SHA of `origin/main` post-fetch.
- If currently on `slice/<change-id>`: rebases against `origin/main`.
  - On conflict: aborts the rebase, prints a human-readable error, exits
    1. The human reviewer is the safety net (do NOT auto-resolve).
  - No-op if already on top of origin/main.
- If currently on a different branch: skips the rebase step, just records
  fields. (The AI may have invoked this BEFORE creating the slice branch;
  that's allowed — fields will be re-set if the AI invokes again post-
  branch-creation.)
- Sets `Branch` + `Base SHA` fields on the project item titled
  `<change-id>`. Creates the fields if absent (calls the same helpers as
  `bootstrap_gh_project.ensure_trace_fields`).

Idempotent: re-running with same args produces same final state.

Exit codes
----------
    0 — success (fields set, rebase clean or skipped)
    1 — rebase conflict; human action required (rebase aborted)
    2 — setup error (gh unavailable, project / item not found, dirty tree)
    3 — unrecoverable GraphQL error
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

# Force UTF-8 stdio.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, OSError):
        pass

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.bootstrap_gh_project import (  # noqa: E402
    list_fields,
    list_items,
    lookup_project,
    _emit,
    _gh_available,
    _gh_graphql,
    ensure_trace_fields,
)


def _git(args: list[str], *, check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        check=check,
        capture_output=capture,
        text=True,
        encoding="utf-8",
    )


def _verify_clean_tree() -> None:
    """Raise RuntimeError if the working tree is dirty."""
    r = _git(["status", "--porcelain"])
    dirty = r.stdout.strip()
    if dirty:
        raise RuntimeError(
            "working tree is dirty. Commit or stash before running "
            "/opsx:apply companion. Output:\n" + dirty
        )


def _current_branch() -> str:
    r = _git(["rev-parse", "--abbrev-ref", "HEAD"])
    return r.stdout.strip()


def _fetch_origin() -> None:
    print("→ git fetch origin")
    _git(["fetch", "origin", "--quiet"], capture=False)


def _capture_base_sha() -> str:
    """Short SHA of `origin/main` HEAD (post-fetch)."""
    r = _git(["rev-parse", "--short", "origin/main"])
    return r.stdout.strip()


def _rebase_onto_main(slice_branch: str) -> None:
    """Rebase the slice branch on top of origin/main. Aborts on conflict."""
    print(f"→ git rebase origin/main (on {slice_branch})")
    r = _git(["rebase", "origin/main"], check=False, capture=True)
    if r.returncode == 0:
        print("  rebase clean (no-op or fast-forward applied)")
        return
    # Abort the rebase to leave the workspace in a clean state.
    _git(["rebase", "--abort"], check=False, capture=True)
    raise RuntimeError(
        f"rebase of {slice_branch} onto origin/main has conflicts. "
        "Aborted. Resolve manually:\n"
        f"  git rebase origin/main\n"
        "  # resolve conflicts, git rebase --continue\n"
        "  # OR: git rebase --abort if you want to give up\n"
        "Per release-management.md §6.5: AI must NOT auto-resolve. "
        "Notify the human reviewer."
    )


def set_item_text_field(
    project_id: str, item_id: str, field_id: str, value: str, *, dry_run: bool
) -> None:
    """Set a TEXT field on a project item via GraphQL."""
    if dry_run:
        return
    mutation = """
    mutation($project_id: ID!, $item_id: ID!, $field_id: ID!, $value: String!) {
      updateProjectV2ItemFieldValue(input: {
        projectId: $project_id,
        itemId: $item_id,
        fieldId: $field_id,
        value: { text: $value }
      }) {
        projectV2Item { id }
      }
    }
    """
    _gh_graphql(
        mutation,
        project_id=project_id,
        item_id=item_id,
        field_id=field_id,
        value=value,
    )


def run(
    *,
    change_id: str,
    owner: str,
    project_number: int,
    repo: str | None,
    dry_run: bool,
) -> int:
    if not _gh_available():
        print("error: gh CLI not authenticated; run `gh auth login` first", file=sys.stderr)
        return 2

    _emit(
        "opsx_apply_companion.start",
        change_id=change_id,
        owner=owner,
        project_number=project_number,
        repo=repo,
        dry_run=dry_run,
    )

    # 1. Verify clean tree.
    try:
        _verify_clean_tree()
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    # 2. Fetch origin.
    if dry_run:
        print("→ would: git fetch origin (dry-run)")
    else:
        _fetch_origin()

    # 3. Capture base SHA.
    if dry_run:
        base_sha = "<dry-run>"
        print(f"→ would: capture base SHA from origin/main (dry-run)")
    else:
        base_sha = _capture_base_sha()
        print(f"→ Base SHA = {base_sha} (origin/main HEAD)")

    # 4. Rebase if on slice branch.
    expected_branch = f"slice/{change_id}"
    current = _current_branch()
    if current == expected_branch:
        if dry_run:
            print(f"→ would: git rebase origin/main on {current} (dry-run)")
        else:
            try:
                _rebase_onto_main(current)
            except RuntimeError as e:
                print(f"error: {e}", file=sys.stderr)
                return 1
    else:
        print(
            f"→ skipping rebase: current branch is {current!r}, expected "
            f"{expected_branch!r}. Either you haven't created the slice "
            "branch yet (in which case this companion will run again "
            "post-creation) or you're on a different branch."
        )

    # 5. Find project + item, ensure trace fields exist, set values.
    try:
        proj = lookup_project(owner, project_number)
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    fields = list_fields(proj.id)
    # Ensure Branch + Base SHA fields exist.
    trace_added = ensure_trace_fields(proj.id, fields, dry_run=dry_run)
    if trace_added:
        # Re-fetch fields after creation.
        fields = list_fields(proj.id) if not dry_run else fields
    branch_field = next((f for f in fields if f.name == "Branch"), None)
    sha_field = next((f for f in fields if f.name == "Base SHA"), None)
    if branch_field is None or sha_field is None:
        print(
            "error: Branch and/or Base SHA fields missing on project; "
            "run `bootstrap_gh_project.py --profile auto` first.",
            file=sys.stderr,
        )
        return 2

    items = list_items(proj.id)
    item = next((it for it in items if it.title == change_id), None)
    if item is None:
        print(
            f"error: no project item with title {change_id!r}; "
            "run `bootstrap_gh_project.py --slicing-file docs/openspec-slice.md` "
            "to create it.",
            file=sys.stderr,
        )
        return 2

    if dry_run:
        print(f"→ would: set Branch={expected_branch!r} on item {change_id!r} (dry-run)")
        print(f"→ would: set Base SHA={base_sha!r} on item {change_id!r} (dry-run)")
    else:
        set_item_text_field(
            proj.id, item.id, branch_field.id, expected_branch, dry_run=dry_run
        )
        set_item_text_field(
            proj.id, item.id, sha_field.id, base_sha, dry_run=dry_run
        )
        print(f"→ Set Branch={expected_branch} on item {change_id!r}")
        print(f"→ Set Base SHA={base_sha} on item {change_id!r}")

    _emit(
        "opsx_apply_companion.complete",
        change_id=change_id,
        branch=expected_branch,
        base_sha=base_sha,
        rebased=(current == expected_branch),
        dry_run=dry_run,
    )
    print(f"✓ /opsx:apply companion done — change_id={change_id}")
    return 0


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description=(
            "Branch + Base SHA capture + pre-flight rebase before /opsx:apply "
            "implementation work. Per release-management.md §6.5."
        )
    )
    p.add_argument(
        "--change-id",
        required=True,
        help="OpenSpec change-id (kebab-case folder name under openspec/changes/)",
    )
    p.add_argument("--owner", required=True, help="GH user or org login")
    p.add_argument("--project-number", required=True, type=int)
    p.add_argument(
        "--repo",
        default=None,
        metavar="owner/name",
        help="Consumer repo (informational; not strictly required)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print intended steps without applying them",
    )
    args = p.parse_args(argv)

    try:
        return run(
            change_id=args.change_id,
            owner=args.owner,
            project_number=args.project_number,
            repo=args.repo,
            dry_run=args.dry_run,
        )
    except RuntimeError as e:
        print(f"error: {e}", file=sys.stderr)
        _emit("opsx_apply_companion.failed", reason=str(e))
        return 3


if __name__ == "__main__":
    sys.exit(main())
