/* Auto-generated by scripts/build_ui_sidecars.py. DO NOT EDIT MANUALLY. */
/* Source of truth: defaults.json (sibling). Loaded via <script src> so the config
   UI can read this inventory under file:// where fetch() is blocked. */
window.DEFAULTS = {
  "schema": "ai-playbook-config/v1",
  "generated_at": "1970-01-01T00:00:00Z",
  "generated_by": "defaults",
  "rules": {},
  "features": {
    "caveman": {
      "enabled": false,
      "mode": "full",
      "components": {
        "response_style": false,
        "compress_docs": false,
        "subagents_cavecrew": false,
        "commit_caveman": false,
        "review_caveman": false,
        "mcp_shrink": false
      }
    },
    "graphify": {
      "enabled": false,
      "components": {
        "agent_guidance": false,
        "gitignore_hygiene": false,
        "enforce_skill": false
      }
    },
    "ponytail": {
      "enabled": false,
      "mode": "full",
      "components": {
        "code_style": false,
        "review_ponytail": false,
        "audit_ponytail": false,
        "debt_ponytail": false
      }
    }
  },
  "global_flags": {
    "llm_routing_strict": false
  }
};
