"""Render ``.gitignore`` from template + bundle.

Strategy: the template defines the playbook-managed patterns inside the
``id=playbook-patterns`` marker block. Consumer extras
(``bundle.gitignore_extras.patterns``) are appended OUTSIDE the marker
block, after a `# >>> consumer patterns` separator.

If the current ``.gitignore`` text is provided (for the in-place update
case), any consumer lines OUTSIDE the marker block are merged with the
bundle extras (de-duplicated, order preserved).
"""
from __future__ import annotations

from scripts._marker_blocks import CommentStyle, parse_blocks
from scripts._template_classifier import compute_sha


_CONSUMER_HEADER = "# >>> consumer patterns (preserved across apply_config) >>>"


def _inject_sha_into_markers(text: str) -> str:
    parsed = parse_blocks(text, CommentStyle.HASH)
    if not parsed.blocks:
        return text
    from scripts._marker_blocks import MarkerBlock, write_blocks
    desired = {
        bid: MarkerBlock(id=bid, content=block.content, sha=compute_sha(block.content),
                         style=CommentStyle.HASH)
        for bid, block in parsed.blocks.items()
    }
    return write_blocks(text, desired, style=CommentStyle.HASH)


def render(
    *,
    template: str,
    substitutions: dict[str, str],
    bundle: dict,
    current_text: str | None = None,
) -> str:
    """Return the final .gitignore content.

    ``current_text``: when provided, any lines outside the playbook marker
    block in the current file are preserved verbatim. The bundle's extras
    are then appended (de-duplicated against the preserved lines).
    """
    body = template
    # No standard {{PLACEHOLDER}} substitutions in .gitignore today, but
    # leave the loop so future templates can lean on it.
    for key, value in substitutions.items():
        if value is not None:
            body = body.replace("{{" + key + "}}", str(value))
    body = _inject_sha_into_markers(body)

    # Collect extras from bundle.
    extras: list[str] = list((bundle.get("gitignore_extras") or {}).get("patterns") or [])

    # Preserve lines from current_text outside any marker block.
    preserved: list[str] = []
    if current_text:
        parsed_current = parse_blocks(current_text, CommentStyle.HASH)
        for segment in parsed_current.custom_segments:
            for line in segment.splitlines():
                stripped = line.rstrip()
                if not stripped:
                    continue
                if stripped.startswith("# Generated by ai-playbook"):
                    continue
                if stripped == _CONSUMER_HEADER:
                    continue
                if stripped.startswith("# >>> ") and "ai-playbook" in stripped:
                    continue
                if stripped.startswith("# <<< ") and "ai-playbook" in stripped:
                    continue
                preserved.append(stripped)

    # De-duplicate while preserving order, preserved first then bundle extras.
    seen: set[str] = set()
    final_extras: list[str] = []
    for line in [*preserved, *extras]:
        if line in seen:
            continue
        seen.add(line)
        final_extras.append(line)

    if final_extras:
        if not body.endswith("\n"):
            body += "\n"
        body += "\n" + _CONSUMER_HEADER + "\n"
        body += "\n".join(final_extras) + "\n"

    return body


__all__ = ["render"]
